FROM golang:1.22.4-bookworm

ARG GORELEASER_VERSION=2.5.0

# Build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    make \
    cmake \
    rpm \
    && rm -rf /var/lib/apt/lists/*

# Install GoReleaser
RUN curl -sfL "https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz" \
    | tar -C /usr/local/bin -xzf - goreleaser \
    && goreleaser --version

# Install go-licenses
RUN go install github.com/google/go-licenses@latest

ENV GOTOOLCHAIN=local

RUN git config --global --add safe.directory /build

WORKDIR /build
