// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type BpfsyscallBpfSyscallEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Cmd         uint32
	ProgType    uint32
	InsnCnt     uint32
	AttachType  uint32
	ObjName     [16]int8
	_           [4]byte
}

// LoadBpfsyscall returns the embedded CollectionSpec for Bpfsyscall.
func LoadBpfsyscall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfsyscallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpfsyscall: %w", err)
	}

	return spec, err
}

// LoadBpfsyscallObjects loads Bpfsyscall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfsyscallObjects
//	*BpfsyscallPrograms
//	*BpfsyscallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfsyscallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfsyscall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfsyscallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfsyscallSpecs struct {
	BpfsyscallProgramSpecs
	BpfsyscallMapSpecs
}

// BpfsyscallSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfsyscallProgramSpecs struct {
	TracepointSyscallsSysEnterBpf *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_bpf"`
	TracepointSyscallsSysExitBpf  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_bpf"`
}

// BpfsyscallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfsyscallMapSpecs struct {
	BpfSyscallEvents *ebpf.MapSpec `ebpf:"bpf_syscall_events"`
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
}

// BpfsyscallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfsyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfsyscallObjects struct {
	BpfsyscallPrograms
	BpfsyscallMaps
}

func (o *BpfsyscallObjects) Close() error {
	return _BpfsyscallClose(
		&o.BpfsyscallPrograms,
		&o.BpfsyscallMaps,
	)
}

// BpfsyscallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfsyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfsyscallMaps struct {
	BpfSyscallEvents *ebpf.Map `ebpf:"bpf_syscall_events"`
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
}

func (m *BpfsyscallMaps) Close() error {
	return _BpfsyscallClose(
		m.BpfSyscallEvents,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// BpfsyscallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfsyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfsyscallPrograms struct {
	TracepointSyscallsSysEnterBpf *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_bpf"`
	TracepointSyscallsSysExitBpf  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_bpf"`
}

func (p *BpfsyscallPrograms) Close() error {
	return _BpfsyscallClose(
		p.TracepointSyscallsSysEnterBpf,
		p.TracepointSyscallsSysExitBpf,
	)
}

func _BpfsyscallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfsyscall_bpfeb.o
var _BpfsyscallBytes []byte
