// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type CapsCapsetEvent struct {
	TimestampNs    uint64
	EventType      uint32
	Pid            uint32
	Ppid           uint32
	Uid            uint32
	Gid            uint32
	Comm           [16]int8
	TargetPid      uint32
	CapVersion     uint32
	_              [4]byte
	CapEffective   uint64
	CapPermitted   uint64
	CapInheritable uint64
	RetCode        int32
	_              [4]byte
}

// LoadCaps returns the embedded CollectionSpec for Caps.
func LoadCaps() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CapsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Caps: %w", err)
	}

	return spec, err
}

// LoadCapsObjects loads Caps and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CapsObjects
//	*CapsPrograms
//	*CapsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCapsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCaps()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CapsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapsSpecs struct {
	CapsProgramSpecs
	CapsMapSpecs
}

// CapsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapsProgramSpecs struct {
	TracepointSyscallsSysEnterCapset *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_capset"`
}

// CapsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapsMapSpecs struct {
	CapsetEvents  *ebpf.MapSpec `ebpf:"capset_events"`
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
}

// CapsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCapsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapsObjects struct {
	CapsPrograms
	CapsMaps
}

func (o *CapsObjects) Close() error {
	return _CapsClose(
		&o.CapsPrograms,
		&o.CapsMaps,
	)
}

// CapsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCapsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapsMaps struct {
	CapsetEvents  *ebpf.Map `ebpf:"capset_events"`
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
}

func (m *CapsMaps) Close() error {
	return _CapsClose(
		m.CapsetEvents,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// CapsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCapsObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapsPrograms struct {
	TracepointSyscallsSysEnterCapset *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_capset"`
}

func (p *CapsPrograms) Close() error {
	return _CapsClose(
		p.TracepointSyscallsSysEnterCapset,
	)
}

func _CapsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed caps_bpfeb.o
var _CapsBytes []byte
