// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type CredhooksCredEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	NewUid      uint32
	NewEuid     uint32
	NewGid      uint32
	NewEgid     uint32
	ExitCode    int32
	RetCode     int32
	_           [4]byte
}

// LoadCredhooks returns the embedded CollectionSpec for Credhooks.
func LoadCredhooks() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CredhooksBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Credhooks: %w", err)
	}

	return spec, err
}

// LoadCredhooksObjects loads Credhooks and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CredhooksObjects
//	*CredhooksPrograms
//	*CredhooksMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCredhooksObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCredhooks()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CredhooksSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredhooksSpecs struct {
	CredhooksProgramSpecs
	CredhooksMapSpecs
}

// CredhooksSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredhooksProgramSpecs struct {
	KprobeCommitCreds *ebpf.ProgramSpec `ebpf:"kprobe_commit_creds"`
	KprobeDoExit      *ebpf.ProgramSpec `ebpf:"kprobe_do_exit"`
}

// CredhooksMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredhooksMapSpecs struct {
	CredEvents    *ebpf.MapSpec `ebpf:"cred_events"`
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
}

// CredhooksObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCredhooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredhooksObjects struct {
	CredhooksPrograms
	CredhooksMaps
}

func (o *CredhooksObjects) Close() error {
	return _CredhooksClose(
		&o.CredhooksPrograms,
		&o.CredhooksMaps,
	)
}

// CredhooksMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCredhooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredhooksMaps struct {
	CredEvents    *ebpf.Map `ebpf:"cred_events"`
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
}

func (m *CredhooksMaps) Close() error {
	return _CredhooksClose(
		m.CredEvents,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// CredhooksPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCredhooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredhooksPrograms struct {
	KprobeCommitCreds *ebpf.Program `ebpf:"kprobe_commit_creds"`
	KprobeDoExit      *ebpf.Program `ebpf:"kprobe_do_exit"`
}

func (p *CredhooksPrograms) Close() error {
	return _CredhooksClose(
		p.KprobeCommitCreds,
		p.KprobeDoExit,
	)
}

func _CredhooksClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed credhooks_bpfeb.o
var _CredhooksBytes []byte
