// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type DataexfilDataexfilEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	FdIn        int32
	FdOut       int32
	_           [4]byte
	Len         uint64
	Flags       uint32
	RetCode     int32
}

// LoadDataexfil returns the embedded CollectionSpec for Dataexfil.
func LoadDataexfil() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DataexfilBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Dataexfil: %w", err)
	}

	return spec, err
}

// LoadDataexfilObjects loads Dataexfil and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DataexfilObjects
//	*DataexfilPrograms
//	*DataexfilMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDataexfilObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDataexfil()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DataexfilSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DataexfilSpecs struct {
	DataexfilProgramSpecs
	DataexfilMapSpecs
}

// DataexfilSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DataexfilProgramSpecs struct {
	TracepointSyscallsSysEnterCopyFileRange *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_copy_file_range"`
	TracepointSyscallsSysEnterSendfile64    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendfile64"`
	TracepointSyscallsSysEnterSplice        *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_splice"`
	TracepointSyscallsSysEnterTee           *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tee"`
}

// DataexfilMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DataexfilMapSpecs struct {
	DataexfilEvents *ebpf.MapSpec `ebpf:"dataexfil_events"`
	DiscardComms    *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids     *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats    *ebpf.MapSpec `ebpf:"discard_stats"`
}

// DataexfilObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDataexfilObjects or ebpf.CollectionSpec.LoadAndAssign.
type DataexfilObjects struct {
	DataexfilPrograms
	DataexfilMaps
}

func (o *DataexfilObjects) Close() error {
	return _DataexfilClose(
		&o.DataexfilPrograms,
		&o.DataexfilMaps,
	)
}

// DataexfilMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDataexfilObjects or ebpf.CollectionSpec.LoadAndAssign.
type DataexfilMaps struct {
	DataexfilEvents *ebpf.Map `ebpf:"dataexfil_events"`
	DiscardComms    *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.Map `ebpf:"discard_config"`
	DiscardPids     *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats    *ebpf.Map `ebpf:"discard_stats"`
}

func (m *DataexfilMaps) Close() error {
	return _DataexfilClose(
		m.DataexfilEvents,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// DataexfilPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDataexfilObjects or ebpf.CollectionSpec.LoadAndAssign.
type DataexfilPrograms struct {
	TracepointSyscallsSysEnterCopyFileRange *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_copy_file_range"`
	TracepointSyscallsSysEnterSendfile64    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendfile64"`
	TracepointSyscallsSysEnterSplice        *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_splice"`
	TracepointSyscallsSysEnterTee           *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tee"`
}

func (p *DataexfilPrograms) Close() error {
	return _DataexfilClose(
		p.TracepointSyscallsSysEnterCopyFileRange,
		p.TracepointSyscallsSysEnterSendfile64,
		p.TracepointSyscallsSysEnterSplice,
		p.TracepointSyscallsSysEnterTee,
	)
}

func _DataexfilClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dataexfil_bpfel.o
var _DataexfilBytes []byte
