// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type DiropsDiropsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Path        [256]int8
	Path2       [256]int8
	Fd          int32
	RetCode     int32
	_           [4]byte
}

// LoadDirops returns the embedded CollectionSpec for Dirops.
func LoadDirops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DiropsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Dirops: %w", err)
	}

	return spec, err
}

// LoadDiropsObjects loads Dirops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DiropsObjects
//	*DiropsPrograms
//	*DiropsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDiropsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDirops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DiropsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DiropsSpecs struct {
	DiropsProgramSpecs
	DiropsMapSpecs
}

// DiropsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DiropsProgramSpecs struct {
	TracepointSyscallsSysEnterChdir     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chdir"`
	TracepointSyscallsSysEnterChroot    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chroot"`
	TracepointSyscallsSysEnterFchdir    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchdir"`
	TracepointSyscallsSysEnterPivotRoot *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_pivot_root"`
}

// DiropsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DiropsMapSpecs struct {
	DiropsEvents  *ebpf.MapSpec `ebpf:"dirops_events"`
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
}

// DiropsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDiropsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DiropsObjects struct {
	DiropsPrograms
	DiropsMaps
}

func (o *DiropsObjects) Close() error {
	return _DiropsClose(
		&o.DiropsPrograms,
		&o.DiropsMaps,
	)
}

// DiropsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDiropsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DiropsMaps struct {
	DiropsEvents  *ebpf.Map `ebpf:"dirops_events"`
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
}

func (m *DiropsMaps) Close() error {
	return _DiropsClose(
		m.DiropsEvents,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// DiropsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDiropsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DiropsPrograms struct {
	TracepointSyscallsSysEnterChdir     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chdir"`
	TracepointSyscallsSysEnterChroot    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chroot"`
	TracepointSyscallsSysEnterFchdir    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchdir"`
	TracepointSyscallsSysEnterPivotRoot *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_pivot_root"`
}

func (p *DiropsPrograms) Close() error {
	return _DiropsClose(
		p.TracepointSyscallsSysEnterChdir,
		p.TracepointSyscallsSysEnterChroot,
		p.TracepointSyscallsSysEnterFchdir,
		p.TracepointSyscallsSysEnterPivotRoot,
	)
}

func _DiropsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dirops_bpfeb.o
var _DiropsBytes []byte
