// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type DnsDnsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Id          uint16
	Qtype       uint16
	Qclass      uint16
	Family      uint16
	Dport       uint16
	NameLen     uint16
	Daddr       [16]uint8
	Qname       [128]int8
}

// LoadDns returns the embedded CollectionSpec for Dns.
func LoadDns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Dns: %w", err)
	}

	return spec, err
}

// LoadDnsObjects loads Dns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DnsObjects
//	*DnsPrograms
//	*DnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDnsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsSpecs struct {
	DnsProgramSpecs
	DnsMapSpecs
}

// DnsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsProgramSpecs struct {
	TracepointSyscallsSysEnterSendmsg *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendmsg"`
	TracepointSyscallsSysEnterSendto  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
}

// DnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	DnsEvents     *ebpf.MapSpec `ebpf:"dns_events"`
}

// DnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsObjects struct {
	DnsPrograms
	DnsMaps
}

func (o *DnsObjects) Close() error {
	return _DnsClose(
		&o.DnsPrograms,
		&o.DnsMaps,
	)
}

// DnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	DnsEvents     *ebpf.Map `ebpf:"dns_events"`
}

func (m *DnsMaps) Close() error {
	return _DnsClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.DnsEvents,
	)
}

// DnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsPrograms struct {
	TracepointSyscallsSysEnterSendmsg *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendmsg"`
	TracepointSyscallsSysEnterSendto  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
}

func (p *DnsPrograms) Close() error {
	return _DnsClose(
		p.TracepointSyscallsSysEnterSendmsg,
		p.TracepointSyscallsSysEnterSendto,
	)
}

func _DnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dns_bpfeb.o
var _DnsBytes []byte
