// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ExecveExecveCtx struct{ Active uint8 }

type ExecveExecveEvent struct {
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Filename    [256]int8
	Args        [256]int8
	ArgsCount   uint32
	RetCode     uint32
}

// LoadExecve returns the embedded CollectionSpec for Execve.
func LoadExecve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Execve: %w", err)
	}

	return spec, err
}

// LoadExecveObjects loads Execve and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecveObjects
//	*ExecvePrograms
//	*ExecveMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecveSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveSpecs struct {
	ExecveProgramSpecs
	ExecveMapSpecs
}

// ExecveSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveProgramSpecs struct {
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysExitExecve  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_execve"`
}

// ExecveMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	ExecveContext *ebpf.MapSpec `ebpf:"execve_context"`
}

// ExecveObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveObjects struct {
	ExecvePrograms
	ExecveMaps
}

func (o *ExecveObjects) Close() error {
	return _ExecveClose(
		&o.ExecvePrograms,
		&o.ExecveMaps,
	)
}

// ExecveMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	Events        *ebpf.Map `ebpf:"events"`
	ExecveContext *ebpf.Map `ebpf:"execve_context"`
}

func (m *ExecveMaps) Close() error {
	return _ExecveClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.Events,
		m.ExecveContext,
	)
}

// ExecvePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecvePrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysExitExecve  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_execve"`
}

func (p *ExecvePrograms) Close() error {
	return _ExecveClose(
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysExitExecve,
	)
}

func _ExecveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execve_bpfeb.o
var _ExecveBytes []byte
