// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type fileopsFileEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Filename    [256]int8
	Filename2   [256]int8
	Flags       int32
	RetCode     int32
	_           [4]byte
}

// loadFileops returns the embedded CollectionSpec for fileops.
func loadFileops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fileops: %w", err)
	}

	return spec, err
}

// loadFileopsObjects loads fileops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileopsObjects
//	*fileopsPrograms
//	*fileopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileopsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFileops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopsSpecs struct {
	fileopsProgramSpecs
	fileopsMapSpecs
}

// fileopsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopsProgramSpecs struct {
	TracepointSyscallsSysEnterFchmodat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchmodat"`
	TracepointSyscallsSysEnterOpenat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterRenameat2 *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_renameat2"`
	TracepointSyscallsSysEnterUnlinkat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unlinkat"`
}

// fileopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopsMapSpecs struct {
	FileEvents *ebpf.MapSpec `ebpf:"file_events"`
}

// fileopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopsObjects struct {
	fileopsPrograms
	fileopsMaps
}

func (o *fileopsObjects) Close() error {
	return _FileopsClose(
		&o.fileopsPrograms,
		&o.fileopsMaps,
	)
}

// fileopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopsMaps struct {
	FileEvents *ebpf.Map `ebpf:"file_events"`
}

func (m *fileopsMaps) Close() error {
	return _FileopsClose(
		m.FileEvents,
	)
}

// fileopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopsPrograms struct {
	TracepointSyscallsSysEnterFchmodat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchmodat"`
	TracepointSyscallsSysEnterOpenat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterRenameat2 *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_renameat2"`
	TracepointSyscallsSysEnterUnlinkat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unlinkat"`
}

func (p *fileopsPrograms) Close() error {
	return _FileopsClose(
		p.TracepointSyscallsSysEnterFchmodat,
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysEnterRenameat2,
		p.TracepointSyscallsSysEnterUnlinkat,
	)
}

func _FileopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fileops_bpfeb.o
var _FileopsBytes []byte
