// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ImdsImdsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Family      uint16
	Dport       uint16
	Daddr       [16]uint8
}

// LoadImds returns the embedded CollectionSpec for Imds.
func LoadImds() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ImdsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Imds: %w", err)
	}

	return spec, err
}

// LoadImdsObjects loads Imds and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ImdsObjects
//	*ImdsPrograms
//	*ImdsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadImdsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadImds()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ImdsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ImdsSpecs struct {
	ImdsProgramSpecs
	ImdsMapSpecs
}

// ImdsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ImdsProgramSpecs struct {
	TracepointSyscallsSysEnterConnect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

// ImdsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ImdsMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	ImdsEvents    *ebpf.MapSpec `ebpf:"imds_events"`
}

// ImdsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadImdsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ImdsObjects struct {
	ImdsPrograms
	ImdsMaps
}

func (o *ImdsObjects) Close() error {
	return _ImdsClose(
		&o.ImdsPrograms,
		&o.ImdsMaps,
	)
}

// ImdsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadImdsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ImdsMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	ImdsEvents    *ebpf.Map `ebpf:"imds_events"`
}

func (m *ImdsMaps) Close() error {
	return _ImdsClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.ImdsEvents,
	)
}

// ImdsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadImdsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ImdsPrograms struct {
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

func (p *ImdsPrograms) Close() error {
	return _ImdsClose(
		p.TracepointSyscallsSysEnterConnect,
	)
}

func _ImdsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed imds_bpfel.o
var _ImdsBytes []byte
