// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type IoctlIoctlEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Fd          int32
	Cmd         uint32
	_           [4]byte
	Arg         uint64
	RetCode     int32
	_           [4]byte
}

// LoadIoctl returns the embedded CollectionSpec for Ioctl.
func LoadIoctl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IoctlBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Ioctl: %w", err)
	}

	return spec, err
}

// LoadIoctlObjects loads Ioctl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*IoctlObjects
//	*IoctlPrograms
//	*IoctlMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadIoctlObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadIoctl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// IoctlSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IoctlSpecs struct {
	IoctlProgramSpecs
	IoctlMapSpecs
}

// IoctlSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IoctlProgramSpecs struct {
	TracepointSyscallsSysEnterIoctl *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ioctl"`
}

// IoctlMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IoctlMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	IoctlEvents   *ebpf.MapSpec `ebpf:"ioctl_events"`
}

// IoctlObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadIoctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type IoctlObjects struct {
	IoctlPrograms
	IoctlMaps
}

func (o *IoctlObjects) Close() error {
	return _IoctlClose(
		&o.IoctlPrograms,
		&o.IoctlMaps,
	)
}

// IoctlMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadIoctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type IoctlMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	IoctlEvents   *ebpf.Map `ebpf:"ioctl_events"`
}

func (m *IoctlMaps) Close() error {
	return _IoctlClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.IoctlEvents,
	)
}

// IoctlPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadIoctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type IoctlPrograms struct {
	TracepointSyscallsSysEnterIoctl *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ioctl"`
}

func (p *IoctlPrograms) Close() error {
	return _IoctlClose(
		p.TracepointSyscallsSysEnterIoctl,
	)
}

func _IoctlClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ioctl_bpfeb.o
var _IoctlBytes []byte
