// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type IouringIouringEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	SqEntries   uint32
	SetupFlags  uint32
	Fd          int32
	Opcode      uint32
	NrArgs      uint32
}

// LoadIouring returns the embedded CollectionSpec for Iouring.
func LoadIouring() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IouringBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Iouring: %w", err)
	}

	return spec, err
}

// LoadIouringObjects loads Iouring and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*IouringObjects
//	*IouringPrograms
//	*IouringMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadIouringObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadIouring()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// IouringSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IouringSpecs struct {
	IouringProgramSpecs
	IouringMapSpecs
}

// IouringSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IouringProgramSpecs struct {
	TracepointSyscallsSysEnterIoUringEnter    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_io_uring_enter"`
	TracepointSyscallsSysEnterIoUringRegister *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_io_uring_register"`
	TracepointSyscallsSysEnterIoUringSetup    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_io_uring_setup"`
}

// IouringMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IouringMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	IouringEvents *ebpf.MapSpec `ebpf:"iouring_events"`
}

// IouringObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadIouringObjects or ebpf.CollectionSpec.LoadAndAssign.
type IouringObjects struct {
	IouringPrograms
	IouringMaps
}

func (o *IouringObjects) Close() error {
	return _IouringClose(
		&o.IouringPrograms,
		&o.IouringMaps,
	)
}

// IouringMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadIouringObjects or ebpf.CollectionSpec.LoadAndAssign.
type IouringMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	IouringEvents *ebpf.Map `ebpf:"iouring_events"`
}

func (m *IouringMaps) Close() error {
	return _IouringClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.IouringEvents,
	)
}

// IouringPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadIouringObjects or ebpf.CollectionSpec.LoadAndAssign.
type IouringPrograms struct {
	TracepointSyscallsSysEnterIoUringEnter    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_io_uring_enter"`
	TracepointSyscallsSysEnterIoUringRegister *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_io_uring_register"`
	TracepointSyscallsSysEnterIoUringSetup    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_io_uring_setup"`
}

func (p *IouringPrograms) Close() error {
	return _IouringClose(
		p.TracepointSyscallsSysEnterIoUringEnter,
		p.TracepointSyscallsSysEnterIoUringRegister,
		p.TracepointSyscallsSysEnterIoUringSetup,
	)
}

func _IouringClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iouring_bpfeb.o
var _IouringBytes []byte
