// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type MemfdMemfdEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Name        [64]int8
	Flags       uint32
	Fd          int32
	_           [4]byte
}

// LoadMemfd returns the embedded CollectionSpec for Memfd.
func LoadMemfd() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemfdBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Memfd: %w", err)
	}

	return spec, err
}

// LoadMemfdObjects loads Memfd and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MemfdObjects
//	*MemfdPrograms
//	*MemfdMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMemfdObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMemfd()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MemfdSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemfdSpecs struct {
	MemfdProgramSpecs
	MemfdMapSpecs
}

// MemfdSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemfdProgramSpecs struct {
	TracepointSyscallsSysEnterExecveat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execveat"`
	TracepointSyscallsSysEnterMemfdCreate *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_memfd_create"`
	TracepointSyscallsSysExitMemfdCreate  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_memfd_create"`
}

// MemfdMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemfdMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	MemfdEvents   *ebpf.MapSpec `ebpf:"memfd_events"`
}

// MemfdObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMemfdObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemfdObjects struct {
	MemfdPrograms
	MemfdMaps
}

func (o *MemfdObjects) Close() error {
	return _MemfdClose(
		&o.MemfdPrograms,
		&o.MemfdMaps,
	)
}

// MemfdMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMemfdObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemfdMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	MemfdEvents   *ebpf.Map `ebpf:"memfd_events"`
}

func (m *MemfdMaps) Close() error {
	return _MemfdClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.MemfdEvents,
	)
}

// MemfdPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMemfdObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemfdPrograms struct {
	TracepointSyscallsSysEnterExecveat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execveat"`
	TracepointSyscallsSysEnterMemfdCreate *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_memfd_create"`
	TracepointSyscallsSysExitMemfdCreate  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_memfd_create"`
}

func (p *MemfdPrograms) Close() error {
	return _MemfdClose(
		p.TracepointSyscallsSysEnterExecveat,
		p.TracepointSyscallsSysEnterMemfdCreate,
		p.TracepointSyscallsSysExitMemfdCreate,
	)
}

func _MemfdClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memfd_bpfel.o
var _MemfdBytes []byte
