// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type memoryMemoryEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	_           [4]byte
	Addr        uint64
	Len         uint64
	Prot        uint32
	RetCode     int32
}

// loadMemory returns the embedded CollectionSpec for memory.
func loadMemory() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemoryBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load memory: %w", err)
	}

	return spec, err
}

// loadMemoryObjects loads memory and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*memoryObjects
//	*memoryPrograms
//	*memoryMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMemoryObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMemory()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// memorySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memorySpecs struct {
	memoryProgramSpecs
	memoryMapSpecs
}

// memorySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memoryProgramSpecs struct {
	TracepointSyscallsSysEnterMprotect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
}

// memoryMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memoryMapSpecs struct {
	MemoryEvents *ebpf.MapSpec `ebpf:"memory_events"`
}

// memoryObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type memoryObjects struct {
	memoryPrograms
	memoryMaps
}

func (o *memoryObjects) Close() error {
	return _MemoryClose(
		&o.memoryPrograms,
		&o.memoryMaps,
	)
}

// memoryMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type memoryMaps struct {
	MemoryEvents *ebpf.Map `ebpf:"memory_events"`
}

func (m *memoryMaps) Close() error {
	return _MemoryClose(
		m.MemoryEvents,
	)
}

// memoryPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type memoryPrograms struct {
	TracepointSyscallsSysEnterMprotect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
}

func (p *memoryPrograms) Close() error {
	return _MemoryClose(
		p.TracepointSyscallsSysEnterMprotect,
	)
}

func _MemoryClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memory_bpfel.o
var _MemoryBytes []byte
