// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type MemoryMemoryEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	_           [4]byte
	Addr        uint64
	Len         uint64
	Prot        uint32
	RetCode     int32
	Flags       uint32
	Fd          int32
}

// LoadMemory returns the embedded CollectionSpec for Memory.
func LoadMemory() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemoryBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Memory: %w", err)
	}

	return spec, err
}

// LoadMemoryObjects loads Memory and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MemoryObjects
//	*MemoryPrograms
//	*MemoryMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMemoryObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMemory()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MemorySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemorySpecs struct {
	MemoryProgramSpecs
	MemoryMapSpecs
}

// MemorySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryProgramSpecs struct {
	TracepointSyscallsSysEnterMmap     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mmap"`
	TracepointSyscallsSysEnterMprotect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
}

// MemoryMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	MemoryEvents  *ebpf.MapSpec `ebpf:"memory_events"`
}

// MemoryObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryObjects struct {
	MemoryPrograms
	MemoryMaps
}

func (o *MemoryObjects) Close() error {
	return _MemoryClose(
		&o.MemoryPrograms,
		&o.MemoryMaps,
	)
}

// MemoryMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	MemoryEvents  *ebpf.Map `ebpf:"memory_events"`
}

func (m *MemoryMaps) Close() error {
	return _MemoryClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.MemoryEvents,
	)
}

// MemoryPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryPrograms struct {
	TracepointSyscallsSysEnterMmap     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mmap"`
	TracepointSyscallsSysEnterMprotect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
}

func (p *MemoryPrograms) Close() error {
	return _MemoryClose(
		p.TracepointSyscallsSysEnterMmap,
		p.TracepointSyscallsSysEnterMprotect,
	)
}

func _MemoryClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memory_bpfeb.o
var _MemoryBytes []byte
