// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type moduleModuleEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	ModuleName  [64]int8
	_           [4]byte
	ModuleSize  uint64
	Flags       int32
	RetCode     int32
}

// loadModule returns the embedded CollectionSpec for module.
func loadModule() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ModuleBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load module: %w", err)
	}

	return spec, err
}

// loadModuleObjects loads module and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*moduleObjects
//	*modulePrograms
//	*moduleMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadModuleObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadModule()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// moduleSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type moduleSpecs struct {
	moduleProgramSpecs
	moduleMapSpecs
}

// moduleSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type moduleProgramSpecs struct {
	TracepointSyscallsSysEnterDeleteModule *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_delete_module"`
	TracepointSyscallsSysEnterFinitModule  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_finit_module"`
	TracepointSyscallsSysEnterInitModule   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_init_module"`
}

// moduleMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type moduleMapSpecs struct {
	ModuleEvents *ebpf.MapSpec `ebpf:"module_events"`
}

// moduleObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadModuleObjects or ebpf.CollectionSpec.LoadAndAssign.
type moduleObjects struct {
	modulePrograms
	moduleMaps
}

func (o *moduleObjects) Close() error {
	return _ModuleClose(
		&o.modulePrograms,
		&o.moduleMaps,
	)
}

// moduleMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadModuleObjects or ebpf.CollectionSpec.LoadAndAssign.
type moduleMaps struct {
	ModuleEvents *ebpf.Map `ebpf:"module_events"`
}

func (m *moduleMaps) Close() error {
	return _ModuleClose(
		m.ModuleEvents,
	)
}

// modulePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadModuleObjects or ebpf.CollectionSpec.LoadAndAssign.
type modulePrograms struct {
	TracepointSyscallsSysEnterDeleteModule *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_delete_module"`
	TracepointSyscallsSysEnterFinitModule  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_finit_module"`
	TracepointSyscallsSysEnterInitModule   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_init_module"`
}

func (p *modulePrograms) Close() error {
	return _ModuleClose(
		p.TracepointSyscallsSysEnterDeleteModule,
		p.TracepointSyscallsSysEnterFinitModule,
		p.TracepointSyscallsSysEnterInitModule,
	)
}

func _ModuleClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed module_bpfel.o
var _ModuleBytes []byte
