// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ModuleModuleCtx struct {
	EventType  uint32
	Pid        uint32
	Ppid       uint32
	Uid        uint32
	Gid        uint32
	Comm       [16]int8
	ModuleName [64]int8
	_          [4]byte
	ModuleSize uint64
	Flags      int32
	_          [4]byte
}

type ModuleModuleEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	ModuleName  [64]int8
	_           [4]byte
	ModuleSize  uint64
	Flags       int32
	RetCode     int32
}

// LoadModule returns the embedded CollectionSpec for Module.
func LoadModule() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ModuleBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Module: %w", err)
	}

	return spec, err
}

// LoadModuleObjects loads Module and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ModuleObjects
//	*ModulePrograms
//	*ModuleMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadModuleObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadModule()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ModuleSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleSpecs struct {
	ModuleProgramSpecs
	ModuleMapSpecs
}

// ModuleSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleProgramSpecs struct {
	TracepointSyscallsSysEnterDeleteModule *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_delete_module"`
	TracepointSyscallsSysEnterFinitModule  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_finit_module"`
	TracepointSyscallsSysEnterInitModule   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_init_module"`
	TracepointSyscallsSysExitFinitModule   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_finit_module"`
	TracepointSyscallsSysExitInitModule    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_init_module"`
}

// ModuleMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ModuleMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	ModuleContext *ebpf.MapSpec `ebpf:"module_context"`
	ModuleEvents  *ebpf.MapSpec `ebpf:"module_events"`
}

// ModuleObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadModuleObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModuleObjects struct {
	ModulePrograms
	ModuleMaps
}

func (o *ModuleObjects) Close() error {
	return _ModuleClose(
		&o.ModulePrograms,
		&o.ModuleMaps,
	)
}

// ModuleMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadModuleObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModuleMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	ModuleContext *ebpf.Map `ebpf:"module_context"`
	ModuleEvents  *ebpf.Map `ebpf:"module_events"`
}

func (m *ModuleMaps) Close() error {
	return _ModuleClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.ModuleContext,
		m.ModuleEvents,
	)
}

// ModulePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadModuleObjects or ebpf.CollectionSpec.LoadAndAssign.
type ModulePrograms struct {
	TracepointSyscallsSysEnterDeleteModule *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_delete_module"`
	TracepointSyscallsSysEnterFinitModule  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_finit_module"`
	TracepointSyscallsSysEnterInitModule   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_init_module"`
	TracepointSyscallsSysExitFinitModule   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_finit_module"`
	TracepointSyscallsSysExitInitModule    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_init_module"`
}

func (p *ModulePrograms) Close() error {
	return _ModuleClose(
		p.TracepointSyscallsSysEnterDeleteModule,
		p.TracepointSyscallsSysEnterFinitModule,
		p.TracepointSyscallsSysEnterInitModule,
		p.TracepointSyscallsSysExitFinitModule,
		p.TracepointSyscallsSysExitInitModule,
	)
}

func _ModuleClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed module_bpfeb.o
var _ModuleBytes []byte
