// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type MountMountCtx struct {
	Pid    uint32
	Ppid   uint32
	Uid    uint32
	Gid    uint32
	Comm   [16]int8
	Source [256]int8
	Target [256]int8
	Fstype [32]int8
	Flags  uint64
}

type MountMountEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Source      [256]int8
	Target      [256]int8
	Fstype      [32]int8
	_           [4]byte
	Flags       uint64
	RetCode     int32
	_           [4]byte
}

// LoadMount returns the embedded CollectionSpec for Mount.
func LoadMount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Mount: %w", err)
	}

	return spec, err
}

// LoadMountObjects loads Mount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MountObjects
//	*MountPrograms
//	*MountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMountObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountSpecs struct {
	MountProgramSpecs
	MountMapSpecs
}

// MountSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountProgramSpecs struct {
	TracepointSyscallsSysEnterMount  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterUmount *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_umount"`
	TracepointSyscallsSysExitMount   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_mount"`
}

// MountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MountMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	MountContext  *ebpf.MapSpec `ebpf:"mount_context"`
	MountEvents   *ebpf.MapSpec `ebpf:"mount_events"`
}

// MountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountObjects struct {
	MountPrograms
	MountMaps
}

func (o *MountObjects) Close() error {
	return _MountClose(
		&o.MountPrograms,
		&o.MountMaps,
	)
}

// MountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	MountContext  *ebpf.Map `ebpf:"mount_context"`
	MountEvents   *ebpf.Map `ebpf:"mount_events"`
}

func (m *MountMaps) Close() error {
	return _MountClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.MountContext,
		m.MountEvents,
	)
}

// MountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type MountPrograms struct {
	TracepointSyscallsSysEnterMount  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterUmount *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_umount"`
	TracepointSyscallsSysExitMount   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_mount"`
}

func (p *MountPrograms) Close() error {
	return _MountClose(
		p.TracepointSyscallsSysEnterMount,
		p.TracepointSyscallsSysEnterUmount,
		p.TracepointSyscallsSysExitMount,
	)
}

func _MountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mount_bpfel.o
var _MountBytes []byte
