// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type mountMountEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Source      [256]int8
	Target      [256]int8
	Fstype      [32]int8
	_           [4]byte
	Flags       uint64
	RetCode     int32
	_           [4]byte
}

// loadMount returns the embedded CollectionSpec for mount.
func loadMount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mount: %w", err)
	}

	return spec, err
}

// loadMountObjects loads mount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mountObjects
//	*mountPrograms
//	*mountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMountObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mountSpecs struct {
	mountProgramSpecs
	mountMapSpecs
}

// mountSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mountProgramSpecs struct {
	TracepointSyscallsSysEnterMount  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterUmount *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_umount"`
}

// mountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mountMapSpecs struct {
	MountEvents *ebpf.MapSpec `ebpf:"mount_events"`
}

// mountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type mountObjects struct {
	mountPrograms
	mountMaps
}

func (o *mountObjects) Close() error {
	return _MountClose(
		&o.mountPrograms,
		&o.mountMaps,
	)
}

// mountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type mountMaps struct {
	MountEvents *ebpf.Map `ebpf:"mount_events"`
}

func (m *mountMaps) Close() error {
	return _MountClose(
		m.MountEvents,
	)
}

// mountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMountObjects or ebpf.CollectionSpec.LoadAndAssign.
type mountPrograms struct {
	TracepointSyscallsSysEnterMount  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterUmount *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_umount"`
}

func (p *mountPrograms) Close() error {
	return _MountClose(
		p.TracepointSyscallsSysEnterMount,
		p.TracepointSyscallsSysEnterUmount,
	)
}

func _MountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mount_bpfel.o
var _MountBytes []byte
