// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NamespaceNamespaceEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Fd          int32
	Nstype      uint32
	_           [4]byte
	Flags       uint64
	RetCode     int32
	_           [4]byte
}

// LoadNamespace returns the embedded CollectionSpec for Namespace.
func LoadNamespace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NamespaceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Namespace: %w", err)
	}

	return spec, err
}

// LoadNamespaceObjects loads Namespace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NamespaceObjects
//	*NamespacePrograms
//	*NamespaceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNamespaceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNamespace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NamespaceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NamespaceSpecs struct {
	NamespaceProgramSpecs
	NamespaceMapSpecs
}

// NamespaceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NamespaceProgramSpecs struct {
	TracepointSyscallsSysEnterSetns   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setns"`
	TracepointSyscallsSysEnterUnshare *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unshare"`
}

// NamespaceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NamespaceMapSpecs struct {
	DiscardComms    *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids     *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats    *ebpf.MapSpec `ebpf:"discard_stats"`
	NamespaceEvents *ebpf.MapSpec `ebpf:"namespace_events"`
}

// NamespaceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNamespaceObjects or ebpf.CollectionSpec.LoadAndAssign.
type NamespaceObjects struct {
	NamespacePrograms
	NamespaceMaps
}

func (o *NamespaceObjects) Close() error {
	return _NamespaceClose(
		&o.NamespacePrograms,
		&o.NamespaceMaps,
	)
}

// NamespaceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNamespaceObjects or ebpf.CollectionSpec.LoadAndAssign.
type NamespaceMaps struct {
	DiscardComms    *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.Map `ebpf:"discard_config"`
	DiscardPids     *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats    *ebpf.Map `ebpf:"discard_stats"`
	NamespaceEvents *ebpf.Map `ebpf:"namespace_events"`
}

func (m *NamespaceMaps) Close() error {
	return _NamespaceClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.NamespaceEvents,
	)
}

// NamespacePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNamespaceObjects or ebpf.CollectionSpec.LoadAndAssign.
type NamespacePrograms struct {
	TracepointSyscallsSysEnterSetns   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setns"`
	TracepointSyscallsSysEnterUnshare *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unshare"`
}

func (p *NamespacePrograms) Close() error {
	return _NamespaceClose(
		p.TracepointSyscallsSysEnterSetns,
		p.TracepointSyscallsSysEnterUnshare,
	)
}

func _NamespaceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed namespace_bpfeb.o
var _NamespaceBytes []byte
