// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfcredhooksCredEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	NewUid      uint32
	NewEuid     uint32
	NewGid      uint32
	NewEgid     uint32
	ExitCode    int32
	RetCode     int32
	_           [4]byte
}

// LoadPerfcredhooks returns the embedded CollectionSpec for Perfcredhooks.
func LoadPerfcredhooks() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfcredhooksBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfcredhooks: %w", err)
	}

	return spec, err
}

// LoadPerfcredhooksObjects loads Perfcredhooks and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfcredhooksObjects
//	*PerfcredhooksPrograms
//	*PerfcredhooksMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfcredhooksObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfcredhooks()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfcredhooksSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfcredhooksSpecs struct {
	PerfcredhooksProgramSpecs
	PerfcredhooksMapSpecs
}

// PerfcredhooksSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfcredhooksProgramSpecs struct {
	KprobeCommitCreds *ebpf.ProgramSpec `ebpf:"kprobe_commit_creds"`
	KprobeDoExit      *ebpf.ProgramSpec `ebpf:"kprobe_do_exit"`
}

// PerfcredhooksMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfcredhooksMapSpecs struct {
	CredEvents     *ebpf.MapSpec `ebpf:"cred_events"`
	CredEventsHeap *ebpf.MapSpec `ebpf:"cred_events_heap"`
	DiscardComms   *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig  *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids    *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats   *ebpf.MapSpec `ebpf:"discard_stats"`
}

// PerfcredhooksObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfcredhooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfcredhooksObjects struct {
	PerfcredhooksPrograms
	PerfcredhooksMaps
}

func (o *PerfcredhooksObjects) Close() error {
	return _PerfcredhooksClose(
		&o.PerfcredhooksPrograms,
		&o.PerfcredhooksMaps,
	)
}

// PerfcredhooksMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfcredhooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfcredhooksMaps struct {
	CredEvents     *ebpf.Map `ebpf:"cred_events"`
	CredEventsHeap *ebpf.Map `ebpf:"cred_events_heap"`
	DiscardComms   *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig  *ebpf.Map `ebpf:"discard_config"`
	DiscardPids    *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats   *ebpf.Map `ebpf:"discard_stats"`
}

func (m *PerfcredhooksMaps) Close() error {
	return _PerfcredhooksClose(
		m.CredEvents,
		m.CredEventsHeap,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// PerfcredhooksPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfcredhooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfcredhooksPrograms struct {
	KprobeCommitCreds *ebpf.Program `ebpf:"kprobe_commit_creds"`
	KprobeDoExit      *ebpf.Program `ebpf:"kprobe_do_exit"`
}

func (p *PerfcredhooksPrograms) Close() error {
	return _PerfcredhooksClose(
		p.KprobeCommitCreds,
		p.KprobeDoExit,
	)
}

func _PerfcredhooksClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfcredhooks_bpfel.o
var _PerfcredhooksBytes []byte
