// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfmoduleModuleCtx struct {
	EventType  uint32
	Pid        uint32
	Ppid       uint32
	Uid        uint32
	Gid        uint32
	Comm       [16]int8
	ModuleName [64]int8
	_          [4]byte
	ModuleSize uint64
	Flags      int32
	_          [4]byte
}

type PerfmoduleModuleEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	ModuleName  [64]int8
	_           [4]byte
	ModuleSize  uint64
	Flags       int32
	RetCode     int32
}

// LoadPerfmodule returns the embedded CollectionSpec for Perfmodule.
func LoadPerfmodule() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfmoduleBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfmodule: %w", err)
	}

	return spec, err
}

// LoadPerfmoduleObjects loads Perfmodule and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfmoduleObjects
//	*PerfmodulePrograms
//	*PerfmoduleMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfmoduleObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfmodule()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfmoduleSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmoduleSpecs struct {
	PerfmoduleProgramSpecs
	PerfmoduleMapSpecs
}

// PerfmoduleSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmoduleProgramSpecs struct {
	TracepointSyscallsSysEnterDeleteModule *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_delete_module"`
	TracepointSyscallsSysEnterFinitModule  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_finit_module"`
	TracepointSyscallsSysEnterInitModule   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_init_module"`
	TracepointSyscallsSysExitFinitModule   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_finit_module"`
	TracepointSyscallsSysExitInitModule    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_init_module"`
}

// PerfmoduleMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmoduleMapSpecs struct {
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
	ModuleContext    *ebpf.MapSpec `ebpf:"module_context"`
	ModuleEvents     *ebpf.MapSpec `ebpf:"module_events"`
	ModuleEventsHeap *ebpf.MapSpec `ebpf:"module_events_heap"`
}

// PerfmoduleObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmoduleObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmoduleObjects struct {
	PerfmodulePrograms
	PerfmoduleMaps
}

func (o *PerfmoduleObjects) Close() error {
	return _PerfmoduleClose(
		&o.PerfmodulePrograms,
		&o.PerfmoduleMaps,
	)
}

// PerfmoduleMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmoduleObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmoduleMaps struct {
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
	ModuleContext    *ebpf.Map `ebpf:"module_context"`
	ModuleEvents     *ebpf.Map `ebpf:"module_events"`
	ModuleEventsHeap *ebpf.Map `ebpf:"module_events_heap"`
}

func (m *PerfmoduleMaps) Close() error {
	return _PerfmoduleClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.ModuleContext,
		m.ModuleEvents,
		m.ModuleEventsHeap,
	)
}

// PerfmodulePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmoduleObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmodulePrograms struct {
	TracepointSyscallsSysEnterDeleteModule *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_delete_module"`
	TracepointSyscallsSysEnterFinitModule  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_finit_module"`
	TracepointSyscallsSysEnterInitModule   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_init_module"`
	TracepointSyscallsSysExitFinitModule   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_finit_module"`
	TracepointSyscallsSysExitInitModule    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_init_module"`
}

func (p *PerfmodulePrograms) Close() error {
	return _PerfmoduleClose(
		p.TracepointSyscallsSysEnterDeleteModule,
		p.TracepointSyscallsSysEnterFinitModule,
		p.TracepointSyscallsSysEnterInitModule,
		p.TracepointSyscallsSysExitFinitModule,
		p.TracepointSyscallsSysExitInitModule,
	)
}

func _PerfmoduleClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfmodule_bpfel.o
var _PerfmoduleBytes []byte
