// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfdnsDnsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Id          uint16
	Qtype       uint16
	Qclass      uint16
	Family      uint16
	Dport       uint16
	NameLen     uint16
	Daddr       [16]uint8
	Qname       [128]int8
}

// LoadPerfdns returns the embedded CollectionSpec for Perfdns.
func LoadPerfdns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfdnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfdns: %w", err)
	}

	return spec, err
}

// LoadPerfdnsObjects loads Perfdns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfdnsObjects
//	*PerfdnsPrograms
//	*PerfdnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfdnsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfdns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfdnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdnsSpecs struct {
	PerfdnsProgramSpecs
	PerfdnsMapSpecs
}

// PerfdnsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdnsProgramSpecs struct {
	TracepointSyscallsSysEnterSendmsg *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendmsg"`
	TracepointSyscallsSysEnterSendto  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
}

// PerfdnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdnsMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	DnsEvents     *ebpf.MapSpec `ebpf:"dns_events"`
	DnsEventsHeap *ebpf.MapSpec `ebpf:"dns_events_heap"`
}

// PerfdnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdnsObjects struct {
	PerfdnsPrograms
	PerfdnsMaps
}

func (o *PerfdnsObjects) Close() error {
	return _PerfdnsClose(
		&o.PerfdnsPrograms,
		&o.PerfdnsMaps,
	)
}

// PerfdnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdnsMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	DnsEvents     *ebpf.Map `ebpf:"dns_events"`
	DnsEventsHeap *ebpf.Map `ebpf:"dns_events_heap"`
}

func (m *PerfdnsMaps) Close() error {
	return _PerfdnsClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.DnsEvents,
		m.DnsEventsHeap,
	)
}

// PerfdnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdnsPrograms struct {
	TracepointSyscallsSysEnterSendmsg *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendmsg"`
	TracepointSyscallsSysEnterSendto  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
}

func (p *PerfdnsPrograms) Close() error {
	return _PerfdnsClose(
		p.TracepointSyscallsSysEnterSendmsg,
		p.TracepointSyscallsSysEnterSendto,
	)
}

func _PerfdnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfdns_bpfeb.o
var _PerfdnsBytes []byte
