// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfdataexfilDataexfilEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	FdIn        int32
	FdOut       int32
	_           [4]byte
	Len         uint64
	Flags       uint32
	RetCode     int32
}

// LoadPerfdataexfil returns the embedded CollectionSpec for Perfdataexfil.
func LoadPerfdataexfil() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfdataexfilBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfdataexfil: %w", err)
	}

	return spec, err
}

// LoadPerfdataexfilObjects loads Perfdataexfil and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfdataexfilObjects
//	*PerfdataexfilPrograms
//	*PerfdataexfilMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfdataexfilObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfdataexfil()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfdataexfilSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdataexfilSpecs struct {
	PerfdataexfilProgramSpecs
	PerfdataexfilMapSpecs
}

// PerfdataexfilSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdataexfilProgramSpecs struct {
	TracepointSyscallsSysEnterCopyFileRange *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_copy_file_range"`
	TracepointSyscallsSysEnterSendfile64    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendfile64"`
	TracepointSyscallsSysEnterSplice        *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_splice"`
	TracepointSyscallsSysEnterTee           *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tee"`
}

// PerfdataexfilMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdataexfilMapSpecs struct {
	DataexfilEvents     *ebpf.MapSpec `ebpf:"dataexfil_events"`
	DataexfilEventsHeap *ebpf.MapSpec `ebpf:"dataexfil_events_heap"`
	DiscardComms        *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig       *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids         *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats        *ebpf.MapSpec `ebpf:"discard_stats"`
}

// PerfdataexfilObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdataexfilObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdataexfilObjects struct {
	PerfdataexfilPrograms
	PerfdataexfilMaps
}

func (o *PerfdataexfilObjects) Close() error {
	return _PerfdataexfilClose(
		&o.PerfdataexfilPrograms,
		&o.PerfdataexfilMaps,
	)
}

// PerfdataexfilMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdataexfilObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdataexfilMaps struct {
	DataexfilEvents     *ebpf.Map `ebpf:"dataexfil_events"`
	DataexfilEventsHeap *ebpf.Map `ebpf:"dataexfil_events_heap"`
	DiscardComms        *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig       *ebpf.Map `ebpf:"discard_config"`
	DiscardPids         *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats        *ebpf.Map `ebpf:"discard_stats"`
}

func (m *PerfdataexfilMaps) Close() error {
	return _PerfdataexfilClose(
		m.DataexfilEvents,
		m.DataexfilEventsHeap,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// PerfdataexfilPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdataexfilObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdataexfilPrograms struct {
	TracepointSyscallsSysEnterCopyFileRange *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_copy_file_range"`
	TracepointSyscallsSysEnterSendfile64    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendfile64"`
	TracepointSyscallsSysEnterSplice        *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_splice"`
	TracepointSyscallsSysEnterTee           *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tee"`
}

func (p *PerfdataexfilPrograms) Close() error {
	return _PerfdataexfilClose(
		p.TracepointSyscallsSysEnterCopyFileRange,
		p.TracepointSyscallsSysEnterSendfile64,
		p.TracepointSyscallsSysEnterSplice,
		p.TracepointSyscallsSysEnterTee,
	)
}

func _PerfdataexfilClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfdataexfil_bpfel.o
var _PerfdataexfilBytes []byte
