// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfnetworkConnectCtx struct {
	Pid    uint32
	Ppid   uint32
	Uid    uint32
	Gid    uint32
	Comm   [16]int8
	Family uint16
	Dport  uint16
	Daddr  [16]uint8
}

type PerfnetworkNetworkEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Family      uint16
	Sport       uint16
	Dport       uint16
	Protocol    uint16
	Saddr       [16]uint8
	Daddr       [16]uint8
	RetCode     int32
}

// LoadPerfnetwork returns the embedded CollectionSpec for Perfnetwork.
func LoadPerfnetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfnetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfnetwork: %w", err)
	}

	return spec, err
}

// LoadPerfnetworkObjects loads Perfnetwork and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfnetworkObjects
//	*PerfnetworkPrograms
//	*PerfnetworkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfnetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfnetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfnetworkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfnetworkSpecs struct {
	PerfnetworkProgramSpecs
	PerfnetworkMapSpecs
}

// PerfnetworkSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfnetworkProgramSpecs struct {
	TracepointSyscallsSysEnterAccept4 *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_accept4"`
	TracepointSyscallsSysEnterBind    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_bind"`
	TracepointSyscallsSysEnterConnect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterSocket  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_socket"`
	TracepointSyscallsSysExitConnect  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_connect"`
}

// PerfnetworkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfnetworkMapSpecs struct {
	ConnectContext    *ebpf.MapSpec `ebpf:"connect_context"`
	DiscardComms      *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig     *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids       *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats      *ebpf.MapSpec `ebpf:"discard_stats"`
	NetworkEvents     *ebpf.MapSpec `ebpf:"network_events"`
	NetworkEventsHeap *ebpf.MapSpec `ebpf:"network_events_heap"`
}

// PerfnetworkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfnetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfnetworkObjects struct {
	PerfnetworkPrograms
	PerfnetworkMaps
}

func (o *PerfnetworkObjects) Close() error {
	return _PerfnetworkClose(
		&o.PerfnetworkPrograms,
		&o.PerfnetworkMaps,
	)
}

// PerfnetworkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfnetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfnetworkMaps struct {
	ConnectContext    *ebpf.Map `ebpf:"connect_context"`
	DiscardComms      *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig     *ebpf.Map `ebpf:"discard_config"`
	DiscardPids       *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats      *ebpf.Map `ebpf:"discard_stats"`
	NetworkEvents     *ebpf.Map `ebpf:"network_events"`
	NetworkEventsHeap *ebpf.Map `ebpf:"network_events_heap"`
}

func (m *PerfnetworkMaps) Close() error {
	return _PerfnetworkClose(
		m.ConnectContext,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.NetworkEvents,
		m.NetworkEventsHeap,
	)
}

// PerfnetworkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfnetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfnetworkPrograms struct {
	TracepointSyscallsSysEnterAccept4 *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_accept4"`
	TracepointSyscallsSysEnterBind    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_bind"`
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterSocket  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_socket"`
	TracepointSyscallsSysExitConnect  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_connect"`
}

func (p *PerfnetworkPrograms) Close() error {
	return _PerfnetworkClose(
		p.TracepointSyscallsSysEnterAccept4,
		p.TracepointSyscallsSysEnterBind,
		p.TracepointSyscallsSysEnterConnect,
		p.TracepointSyscallsSysEnterSocket,
		p.TracepointSyscallsSysExitConnect,
	)
}

func _PerfnetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfnetwork_bpfeb.o
var _PerfnetworkBytes []byte
