// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfvfshooksPathScratch struct {
	Components [8][64]int8
	CompLen    [8]int32
	Depth      int32
}

type PerfvfshooksVfsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Path        [256]int8
	Path2       [256]int8
	I_mode      uint32
	I_uid       uint32
	_           [4]byte
	I_ino       uint64
	RetCode     int32
	_           [4]byte
}

// LoadPerfvfshooks returns the embedded CollectionSpec for Perfvfshooks.
func LoadPerfvfshooks() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfvfshooksBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfvfshooks: %w", err)
	}

	return spec, err
}

// LoadPerfvfshooksObjects loads Perfvfshooks and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfvfshooksObjects
//	*PerfvfshooksPrograms
//	*PerfvfshooksMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfvfshooksObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfvfshooks()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfvfshooksSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfvfshooksSpecs struct {
	PerfvfshooksProgramSpecs
	PerfvfshooksMapSpecs
}

// PerfvfshooksSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfvfshooksProgramSpecs struct {
	KprobeSecurityInodeSetattr *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_setattr"`
	KprobeVfsOpen              *ebpf.ProgramSpec `ebpf:"kprobe_vfs_open"`
	KprobeVfsRename            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_rename"`
	KprobeVfsUnlink            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_unlink"`
}

// PerfvfshooksMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfvfshooksMapSpecs struct {
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
	VfsDentryScratch *ebpf.MapSpec `ebpf:"vfs_dentry_scratch"`
	VfsEvents        *ebpf.MapSpec `ebpf:"vfs_events"`
	VfsEventsHeap    *ebpf.MapSpec `ebpf:"vfs_events_heap"`
}

// PerfvfshooksObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfvfshooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfvfshooksObjects struct {
	PerfvfshooksPrograms
	PerfvfshooksMaps
}

func (o *PerfvfshooksObjects) Close() error {
	return _PerfvfshooksClose(
		&o.PerfvfshooksPrograms,
		&o.PerfvfshooksMaps,
	)
}

// PerfvfshooksMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfvfshooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfvfshooksMaps struct {
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
	VfsDentryScratch *ebpf.Map `ebpf:"vfs_dentry_scratch"`
	VfsEvents        *ebpf.Map `ebpf:"vfs_events"`
	VfsEventsHeap    *ebpf.Map `ebpf:"vfs_events_heap"`
}

func (m *PerfvfshooksMaps) Close() error {
	return _PerfvfshooksClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.VfsDentryScratch,
		m.VfsEvents,
		m.VfsEventsHeap,
	)
}

// PerfvfshooksPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfvfshooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfvfshooksPrograms struct {
	KprobeSecurityInodeSetattr *ebpf.Program `ebpf:"kprobe_security_inode_setattr"`
	KprobeVfsOpen              *ebpf.Program `ebpf:"kprobe_vfs_open"`
	KprobeVfsRename            *ebpf.Program `ebpf:"kprobe_vfs_rename"`
	KprobeVfsUnlink            *ebpf.Program `ebpf:"kprobe_vfs_unlink"`
}

func (p *PerfvfshooksPrograms) Close() error {
	return _PerfvfshooksClose(
		p.KprobeSecurityInodeSetattr,
		p.KprobeVfsOpen,
		p.KprobeVfsRename,
		p.KprobeVfsUnlink,
	)
}

func _PerfvfshooksClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfvfshooks_bpfeb.o
var _PerfvfshooksBytes []byte
