// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfexecveExecveCtx struct{ Active uint8 }

type PerfexecveExecveEvent struct {
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Filename    [256]int8
	Args        [512]int8
	ArgsCount   uint32
	RetCode     uint32
}

// LoadPerfexecve returns the embedded CollectionSpec for Perfexecve.
func LoadPerfexecve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfexecveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfexecve: %w", err)
	}

	return spec, err
}

// LoadPerfexecveObjects loads Perfexecve and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfexecveObjects
//	*PerfexecvePrograms
//	*PerfexecveMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfexecveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfexecve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfexecveSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfexecveSpecs struct {
	PerfexecveProgramSpecs
	PerfexecveMapSpecs
}

// PerfexecveSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfexecveProgramSpecs struct {
	TracepointSyscallsSysEnterExecve *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysExitExecve  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_execve"`
}

// PerfexecveMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfexecveMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	EventsHeap    *ebpf.MapSpec `ebpf:"events_heap"`
	ExecveContext *ebpf.MapSpec `ebpf:"execve_context"`
}

// PerfexecveObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfexecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfexecveObjects struct {
	PerfexecvePrograms
	PerfexecveMaps
}

func (o *PerfexecveObjects) Close() error {
	return _PerfexecveClose(
		&o.PerfexecvePrograms,
		&o.PerfexecveMaps,
	)
}

// PerfexecveMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfexecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfexecveMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	Events        *ebpf.Map `ebpf:"events"`
	EventsHeap    *ebpf.Map `ebpf:"events_heap"`
	ExecveContext *ebpf.Map `ebpf:"execve_context"`
}

func (m *PerfexecveMaps) Close() error {
	return _PerfexecveClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.Events,
		m.EventsHeap,
		m.ExecveContext,
	)
}

// PerfexecvePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfexecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfexecvePrograms struct {
	TracepointSyscallsSysEnterExecve *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysExitExecve  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_execve"`
}

func (p *PerfexecvePrograms) Close() error {
	return _PerfexecveClose(
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysExitExecve,
	)
}

func _PerfexecveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfexecve_bpfel.o
var _PerfexecveBytes []byte
