// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfdiropsDiropsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Path        [256]int8
	Path2       [256]int8
	Fd          int32
	RetCode     int32
	_           [4]byte
}

// LoadPerfdirops returns the embedded CollectionSpec for Perfdirops.
func LoadPerfdirops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfdiropsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfdirops: %w", err)
	}

	return spec, err
}

// LoadPerfdiropsObjects loads Perfdirops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfdiropsObjects
//	*PerfdiropsPrograms
//	*PerfdiropsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfdiropsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfdirops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfdiropsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdiropsSpecs struct {
	PerfdiropsProgramSpecs
	PerfdiropsMapSpecs
}

// PerfdiropsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdiropsProgramSpecs struct {
	TracepointSyscallsSysEnterChdir     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chdir"`
	TracepointSyscallsSysEnterChroot    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chroot"`
	TracepointSyscallsSysEnterFchdir    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchdir"`
	TracepointSyscallsSysEnterPivotRoot *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_pivot_root"`
}

// PerfdiropsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfdiropsMapSpecs struct {
	DiropsEvents     *ebpf.MapSpec `ebpf:"dirops_events"`
	DiropsEventsHeap *ebpf.MapSpec `ebpf:"dirops_events_heap"`
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
}

// PerfdiropsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdiropsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdiropsObjects struct {
	PerfdiropsPrograms
	PerfdiropsMaps
}

func (o *PerfdiropsObjects) Close() error {
	return _PerfdiropsClose(
		&o.PerfdiropsPrograms,
		&o.PerfdiropsMaps,
	)
}

// PerfdiropsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdiropsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdiropsMaps struct {
	DiropsEvents     *ebpf.Map `ebpf:"dirops_events"`
	DiropsEventsHeap *ebpf.Map `ebpf:"dirops_events_heap"`
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
}

func (m *PerfdiropsMaps) Close() error {
	return _PerfdiropsClose(
		m.DiropsEvents,
		m.DiropsEventsHeap,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// PerfdiropsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfdiropsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfdiropsPrograms struct {
	TracepointSyscallsSysEnterChdir     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chdir"`
	TracepointSyscallsSysEnterChroot    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chroot"`
	TracepointSyscallsSysEnterFchdir    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchdir"`
	TracepointSyscallsSysEnterPivotRoot *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_pivot_root"`
}

func (p *PerfdiropsPrograms) Close() error {
	return _PerfdiropsClose(
		p.TracepointSyscallsSysEnterChdir,
		p.TracepointSyscallsSysEnterChroot,
		p.TracepointSyscallsSysEnterFchdir,
		p.TracepointSyscallsSysEnterPivotRoot,
	)
}

func _PerfdiropsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfdirops_bpfeb.o
var _PerfdiropsBytes []byte
