// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfbpfsyscallBpfSyscallEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Cmd         uint32
	ProgType    uint32
	InsnCnt     uint32
	AttachType  uint32
	ObjName     [16]int8
	_           [4]byte
}

// LoadPerfbpfsyscall returns the embedded CollectionSpec for Perfbpfsyscall.
func LoadPerfbpfsyscall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfbpfsyscallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfbpfsyscall: %w", err)
	}

	return spec, err
}

// LoadPerfbpfsyscallObjects loads Perfbpfsyscall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfbpfsyscallObjects
//	*PerfbpfsyscallPrograms
//	*PerfbpfsyscallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfbpfsyscallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfbpfsyscall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfbpfsyscallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfbpfsyscallSpecs struct {
	PerfbpfsyscallProgramSpecs
	PerfbpfsyscallMapSpecs
}

// PerfbpfsyscallSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfbpfsyscallProgramSpecs struct {
	TracepointSyscallsSysEnterBpf *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_bpf"`
	TracepointSyscallsSysExitBpf  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_bpf"`
}

// PerfbpfsyscallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfbpfsyscallMapSpecs struct {
	BpfSyscallEvents     *ebpf.MapSpec `ebpf:"bpf_syscall_events"`
	BpfSyscallEventsHeap *ebpf.MapSpec `ebpf:"bpf_syscall_events_heap"`
	DiscardComms         *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig        *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids          *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats         *ebpf.MapSpec `ebpf:"discard_stats"`
}

// PerfbpfsyscallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfbpfsyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfbpfsyscallObjects struct {
	PerfbpfsyscallPrograms
	PerfbpfsyscallMaps
}

func (o *PerfbpfsyscallObjects) Close() error {
	return _PerfbpfsyscallClose(
		&o.PerfbpfsyscallPrograms,
		&o.PerfbpfsyscallMaps,
	)
}

// PerfbpfsyscallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfbpfsyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfbpfsyscallMaps struct {
	BpfSyscallEvents     *ebpf.Map `ebpf:"bpf_syscall_events"`
	BpfSyscallEventsHeap *ebpf.Map `ebpf:"bpf_syscall_events_heap"`
	DiscardComms         *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig        *ebpf.Map `ebpf:"discard_config"`
	DiscardPids          *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats         *ebpf.Map `ebpf:"discard_stats"`
}

func (m *PerfbpfsyscallMaps) Close() error {
	return _PerfbpfsyscallClose(
		m.BpfSyscallEvents,
		m.BpfSyscallEventsHeap,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// PerfbpfsyscallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfbpfsyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfbpfsyscallPrograms struct {
	TracepointSyscallsSysEnterBpf *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_bpf"`
	TracepointSyscallsSysExitBpf  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_bpf"`
}

func (p *PerfbpfsyscallPrograms) Close() error {
	return _PerfbpfsyscallClose(
		p.TracepointSyscallsSysEnterBpf,
		p.TracepointSyscallsSysExitBpf,
	)
}

func _PerfbpfsyscallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfbpfsyscall_bpfeb.o
var _PerfbpfsyscallBytes []byte
