// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfprivilegePrivCtx struct {
	EventType uint32
	Pid       uint32
	Ppid      uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	NewUid    uint32
	NewGid    uint32
	NewEuid   uint32
	NewEgid   uint32
}

type PerfprivilegePrivilegeEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	NewUid      uint32
	NewGid      uint32
	NewEuid     uint32
	NewEgid     uint32
	RetCode     int32
}

// LoadPerfprivilege returns the embedded CollectionSpec for Perfprivilege.
func LoadPerfprivilege() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfprivilegeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfprivilege: %w", err)
	}

	return spec, err
}

// LoadPerfprivilegeObjects loads Perfprivilege and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfprivilegeObjects
//	*PerfprivilegePrograms
//	*PerfprivilegeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfprivilegeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfprivilege()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfprivilegeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfprivilegeSpecs struct {
	PerfprivilegeProgramSpecs
	PerfprivilegeMapSpecs
}

// PerfprivilegeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfprivilegeProgramSpecs struct {
	TracepointSyscallsSysEnterSetfsgid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setfsgid"`
	TracepointSyscallsSysEnterSetfsuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setfsuid"`
	TracepointSyscallsSysEnterSetgid    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetregid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetresgid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setresgid"`
	TracepointSyscallsSysEnterSetresuid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setresuid"`
	TracepointSyscallsSysEnterSetreuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetuid    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
	TracepointSyscallsSysExitSetgid     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setgid"`
	TracepointSyscallsSysExitSetregid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setregid"`
	TracepointSyscallsSysExitSetreuid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setreuid"`
	TracepointSyscallsSysExitSetuid     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setuid"`
}

// PerfprivilegeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfprivilegeMapSpecs struct {
	DiscardComms        *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig       *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids         *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats        *ebpf.MapSpec `ebpf:"discard_stats"`
	PrivContext         *ebpf.MapSpec `ebpf:"priv_context"`
	PrivilegeEvents     *ebpf.MapSpec `ebpf:"privilege_events"`
	PrivilegeEventsHeap *ebpf.MapSpec `ebpf:"privilege_events_heap"`
}

// PerfprivilegeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfprivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfprivilegeObjects struct {
	PerfprivilegePrograms
	PerfprivilegeMaps
}

func (o *PerfprivilegeObjects) Close() error {
	return _PerfprivilegeClose(
		&o.PerfprivilegePrograms,
		&o.PerfprivilegeMaps,
	)
}

// PerfprivilegeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfprivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfprivilegeMaps struct {
	DiscardComms        *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig       *ebpf.Map `ebpf:"discard_config"`
	DiscardPids         *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats        *ebpf.Map `ebpf:"discard_stats"`
	PrivContext         *ebpf.Map `ebpf:"priv_context"`
	PrivilegeEvents     *ebpf.Map `ebpf:"privilege_events"`
	PrivilegeEventsHeap *ebpf.Map `ebpf:"privilege_events_heap"`
}

func (m *PerfprivilegeMaps) Close() error {
	return _PerfprivilegeClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.PrivContext,
		m.PrivilegeEvents,
		m.PrivilegeEventsHeap,
	)
}

// PerfprivilegePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfprivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfprivilegePrograms struct {
	TracepointSyscallsSysEnterSetfsgid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setfsgid"`
	TracepointSyscallsSysEnterSetfsuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setfsuid"`
	TracepointSyscallsSysEnterSetgid    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetregid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetresgid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setresgid"`
	TracepointSyscallsSysEnterSetresuid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setresuid"`
	TracepointSyscallsSysEnterSetreuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetuid    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
	TracepointSyscallsSysExitSetgid     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setgid"`
	TracepointSyscallsSysExitSetregid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setregid"`
	TracepointSyscallsSysExitSetreuid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setreuid"`
	TracepointSyscallsSysExitSetuid     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setuid"`
}

func (p *PerfprivilegePrograms) Close() error {
	return _PerfprivilegeClose(
		p.TracepointSyscallsSysEnterSetfsgid,
		p.TracepointSyscallsSysEnterSetfsuid,
		p.TracepointSyscallsSysEnterSetgid,
		p.TracepointSyscallsSysEnterSetregid,
		p.TracepointSyscallsSysEnterSetresgid,
		p.TracepointSyscallsSysEnterSetresuid,
		p.TracepointSyscallsSysEnterSetreuid,
		p.TracepointSyscallsSysEnterSetuid,
		p.TracepointSyscallsSysExitSetgid,
		p.TracepointSyscallsSysExitSetregid,
		p.TracepointSyscallsSysExitSetreuid,
		p.TracepointSyscallsSysExitSetuid,
	)
}

func _PerfprivilegeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfprivilege_bpfeb.o
var _PerfprivilegeBytes []byte
