// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfnamespaceNamespaceEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Fd          int32
	Nstype      uint32
	_           [4]byte
	Flags       uint64
	RetCode     int32
	_           [4]byte
}

// LoadPerfnamespace returns the embedded CollectionSpec for Perfnamespace.
func LoadPerfnamespace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfnamespaceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfnamespace: %w", err)
	}

	return spec, err
}

// LoadPerfnamespaceObjects loads Perfnamespace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfnamespaceObjects
//	*PerfnamespacePrograms
//	*PerfnamespaceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfnamespaceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfnamespace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfnamespaceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfnamespaceSpecs struct {
	PerfnamespaceProgramSpecs
	PerfnamespaceMapSpecs
}

// PerfnamespaceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfnamespaceProgramSpecs struct {
	TracepointSyscallsSysEnterSetns   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setns"`
	TracepointSyscallsSysEnterUnshare *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unshare"`
}

// PerfnamespaceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfnamespaceMapSpecs struct {
	DiscardComms        *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig       *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids         *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats        *ebpf.MapSpec `ebpf:"discard_stats"`
	NamespaceEvents     *ebpf.MapSpec `ebpf:"namespace_events"`
	NamespaceEventsHeap *ebpf.MapSpec `ebpf:"namespace_events_heap"`
}

// PerfnamespaceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfnamespaceObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfnamespaceObjects struct {
	PerfnamespacePrograms
	PerfnamespaceMaps
}

func (o *PerfnamespaceObjects) Close() error {
	return _PerfnamespaceClose(
		&o.PerfnamespacePrograms,
		&o.PerfnamespaceMaps,
	)
}

// PerfnamespaceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfnamespaceObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfnamespaceMaps struct {
	DiscardComms        *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig       *ebpf.Map `ebpf:"discard_config"`
	DiscardPids         *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats        *ebpf.Map `ebpf:"discard_stats"`
	NamespaceEvents     *ebpf.Map `ebpf:"namespace_events"`
	NamespaceEventsHeap *ebpf.Map `ebpf:"namespace_events_heap"`
}

func (m *PerfnamespaceMaps) Close() error {
	return _PerfnamespaceClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.NamespaceEvents,
		m.NamespaceEventsHeap,
	)
}

// PerfnamespacePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfnamespaceObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfnamespacePrograms struct {
	TracepointSyscallsSysEnterSetns   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setns"`
	TracepointSyscallsSysEnterUnshare *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unshare"`
}

func (p *PerfnamespacePrograms) Close() error {
	return _PerfnamespaceClose(
		p.TracepointSyscallsSysEnterSetns,
		p.TracepointSyscallsSysEnterUnshare,
	)
}

func _PerfnamespaceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfnamespace_bpfel.o
var _PerfnamespaceBytes []byte
