// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfmountMountCtx struct {
	Pid    uint32
	Ppid   uint32
	Uid    uint32
	Gid    uint32
	Comm   [16]int8
	Source [256]int8
	Target [256]int8
	Fstype [32]int8
	Flags  uint64
}

type PerfmountMountEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Source      [256]int8
	Target      [256]int8
	Fstype      [32]int8
	_           [4]byte
	Flags       uint64
	RetCode     int32
	_           [4]byte
}

// LoadPerfmount returns the embedded CollectionSpec for Perfmount.
func LoadPerfmount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfmountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfmount: %w", err)
	}

	return spec, err
}

// LoadPerfmountObjects loads Perfmount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfmountObjects
//	*PerfmountPrograms
//	*PerfmountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfmountObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfmount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfmountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmountSpecs struct {
	PerfmountProgramSpecs
	PerfmountMapSpecs
}

// PerfmountSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmountProgramSpecs struct {
	TracepointSyscallsSysEnterMount  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterUmount *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_umount"`
	TracepointSyscallsSysExitMount   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_mount"`
}

// PerfmountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmountMapSpecs struct {
	DiscardComms    *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids     *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats    *ebpf.MapSpec `ebpf:"discard_stats"`
	MountContext    *ebpf.MapSpec `ebpf:"mount_context"`
	MountEvents     *ebpf.MapSpec `ebpf:"mount_events"`
	MountEventsHeap *ebpf.MapSpec `ebpf:"mount_events_heap"`
}

// PerfmountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmountObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmountObjects struct {
	PerfmountPrograms
	PerfmountMaps
}

func (o *PerfmountObjects) Close() error {
	return _PerfmountClose(
		&o.PerfmountPrograms,
		&o.PerfmountMaps,
	)
}

// PerfmountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmountObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmountMaps struct {
	DiscardComms    *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.Map `ebpf:"discard_config"`
	DiscardPids     *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats    *ebpf.Map `ebpf:"discard_stats"`
	MountContext    *ebpf.Map `ebpf:"mount_context"`
	MountEvents     *ebpf.Map `ebpf:"mount_events"`
	MountEventsHeap *ebpf.Map `ebpf:"mount_events_heap"`
}

func (m *PerfmountMaps) Close() error {
	return _PerfmountClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.MountContext,
		m.MountEvents,
		m.MountEventsHeap,
	)
}

// PerfmountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmountObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmountPrograms struct {
	TracepointSyscallsSysEnterMount  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterUmount *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_umount"`
	TracepointSyscallsSysExitMount   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_mount"`
}

func (p *PerfmountPrograms) Close() error {
	return _PerfmountClose(
		p.TracepointSyscallsSysEnterMount,
		p.TracepointSyscallsSysEnterUmount,
		p.TracepointSyscallsSysExitMount,
	)
}

func _PerfmountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfmount_bpfel.o
var _PerfmountBytes []byte
