// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfprocessProcessEvent struct {
	TimestampNs   uint64
	EventType     uint32
	Pid           uint32
	Ppid          uint32
	Uid           uint32
	Gid           uint32
	Comm          [16]int8
	TargetPid     uint32
	Sig           int32
	PtraceRequest int32
	CloneFlags    uint64
	RetCode       int32
	_             [4]byte
}

// LoadPerfprocess returns the embedded CollectionSpec for Perfprocess.
func LoadPerfprocess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfprocessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfprocess: %w", err)
	}

	return spec, err
}

// LoadPerfprocessObjects loads Perfprocess and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfprocessObjects
//	*PerfprocessPrograms
//	*PerfprocessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfprocessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfprocess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfprocessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfprocessSpecs struct {
	PerfprocessProgramSpecs
	PerfprocessMapSpecs
}

// PerfprocessSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfprocessProgramSpecs struct {
	TracepointSyscallsSysEnterClone  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterKill   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterPtrace *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
	TracepointSyscallsSysEnterTgkill *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tgkill"`
	TracepointSyscallsSysEnterTkill  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tkill"`
}

// PerfprocessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfprocessMapSpecs struct {
	DiscardComms      *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig     *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids       *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats      *ebpf.MapSpec `ebpf:"discard_stats"`
	ProcessEvents     *ebpf.MapSpec `ebpf:"process_events"`
	ProcessEventsHeap *ebpf.MapSpec `ebpf:"process_events_heap"`
}

// PerfprocessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfprocessObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfprocessObjects struct {
	PerfprocessPrograms
	PerfprocessMaps
}

func (o *PerfprocessObjects) Close() error {
	return _PerfprocessClose(
		&o.PerfprocessPrograms,
		&o.PerfprocessMaps,
	)
}

// PerfprocessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfprocessObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfprocessMaps struct {
	DiscardComms      *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig     *ebpf.Map `ebpf:"discard_config"`
	DiscardPids       *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats      *ebpf.Map `ebpf:"discard_stats"`
	ProcessEvents     *ebpf.Map `ebpf:"process_events"`
	ProcessEventsHeap *ebpf.Map `ebpf:"process_events_heap"`
}

func (m *PerfprocessMaps) Close() error {
	return _PerfprocessClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.ProcessEvents,
		m.ProcessEventsHeap,
	)
}

// PerfprocessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfprocessObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfprocessPrograms struct {
	TracepointSyscallsSysEnterClone  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterKill   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterPtrace *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
	TracepointSyscallsSysEnterTgkill *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tgkill"`
	TracepointSyscallsSysEnterTkill  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tkill"`
}

func (p *PerfprocessPrograms) Close() error {
	return _PerfprocessClose(
		p.TracepointSyscallsSysEnterClone,
		p.TracepointSyscallsSysEnterKill,
		p.TracepointSyscallsSysEnterPtrace,
		p.TracepointSyscallsSysEnterTgkill,
		p.TracepointSyscallsSysEnterTkill,
	)
}

func _PerfprocessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfprocess_bpfel.o
var _PerfprocessBytes []byte
