// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfiouringIouringEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	SqEntries   uint32
	SetupFlags  uint32
	Fd          int32
	Opcode      uint32
	NrArgs      uint32
}

// LoadPerfiouring returns the embedded CollectionSpec for Perfiouring.
func LoadPerfiouring() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfiouringBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfiouring: %w", err)
	}

	return spec, err
}

// LoadPerfiouringObjects loads Perfiouring and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfiouringObjects
//	*PerfiouringPrograms
//	*PerfiouringMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfiouringObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfiouring()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfiouringSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfiouringSpecs struct {
	PerfiouringProgramSpecs
	PerfiouringMapSpecs
}

// PerfiouringSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfiouringProgramSpecs struct {
	TracepointSyscallsSysEnterIoUringEnter    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_io_uring_enter"`
	TracepointSyscallsSysEnterIoUringRegister *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_io_uring_register"`
	TracepointSyscallsSysEnterIoUringSetup    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_io_uring_setup"`
}

// PerfiouringMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfiouringMapSpecs struct {
	DiscardComms      *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig     *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids       *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats      *ebpf.MapSpec `ebpf:"discard_stats"`
	IouringEvents     *ebpf.MapSpec `ebpf:"iouring_events"`
	IouringEventsHeap *ebpf.MapSpec `ebpf:"iouring_events_heap"`
}

// PerfiouringObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfiouringObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfiouringObjects struct {
	PerfiouringPrograms
	PerfiouringMaps
}

func (o *PerfiouringObjects) Close() error {
	return _PerfiouringClose(
		&o.PerfiouringPrograms,
		&o.PerfiouringMaps,
	)
}

// PerfiouringMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfiouringObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfiouringMaps struct {
	DiscardComms      *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig     *ebpf.Map `ebpf:"discard_config"`
	DiscardPids       *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats      *ebpf.Map `ebpf:"discard_stats"`
	IouringEvents     *ebpf.Map `ebpf:"iouring_events"`
	IouringEventsHeap *ebpf.Map `ebpf:"iouring_events_heap"`
}

func (m *PerfiouringMaps) Close() error {
	return _PerfiouringClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.IouringEvents,
		m.IouringEventsHeap,
	)
}

// PerfiouringPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfiouringObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfiouringPrograms struct {
	TracepointSyscallsSysEnterIoUringEnter    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_io_uring_enter"`
	TracepointSyscallsSysEnterIoUringRegister *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_io_uring_register"`
	TracepointSyscallsSysEnterIoUringSetup    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_io_uring_setup"`
}

func (p *PerfiouringPrograms) Close() error {
	return _PerfiouringClose(
		p.TracepointSyscallsSysEnterIoUringEnter,
		p.TracepointSyscallsSysEnterIoUringRegister,
		p.TracepointSyscallsSysEnterIoUringSetup,
	)
}

func _PerfiouringClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfiouring_bpfeb.o
var _PerfiouringBytes []byte
