// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfioctlIoctlEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Fd          int32
	Cmd         uint32
	_           [4]byte
	Arg         uint64
	RetCode     int32
	_           [4]byte
}

// LoadPerfioctl returns the embedded CollectionSpec for Perfioctl.
func LoadPerfioctl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfioctlBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfioctl: %w", err)
	}

	return spec, err
}

// LoadPerfioctlObjects loads Perfioctl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfioctlObjects
//	*PerfioctlPrograms
//	*PerfioctlMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfioctlObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfioctl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfioctlSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfioctlSpecs struct {
	PerfioctlProgramSpecs
	PerfioctlMapSpecs
}

// PerfioctlSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfioctlProgramSpecs struct {
	TracepointSyscallsSysEnterIoctl *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ioctl"`
}

// PerfioctlMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfioctlMapSpecs struct {
	DiscardComms    *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids     *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats    *ebpf.MapSpec `ebpf:"discard_stats"`
	IoctlEvents     *ebpf.MapSpec `ebpf:"ioctl_events"`
	IoctlEventsHeap *ebpf.MapSpec `ebpf:"ioctl_events_heap"`
}

// PerfioctlObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfioctlObjects struct {
	PerfioctlPrograms
	PerfioctlMaps
}

func (o *PerfioctlObjects) Close() error {
	return _PerfioctlClose(
		&o.PerfioctlPrograms,
		&o.PerfioctlMaps,
	)
}

// PerfioctlMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfioctlMaps struct {
	DiscardComms    *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.Map `ebpf:"discard_config"`
	DiscardPids     *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats    *ebpf.Map `ebpf:"discard_stats"`
	IoctlEvents     *ebpf.Map `ebpf:"ioctl_events"`
	IoctlEventsHeap *ebpf.Map `ebpf:"ioctl_events_heap"`
}

func (m *PerfioctlMaps) Close() error {
	return _PerfioctlClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.IoctlEvents,
		m.IoctlEventsHeap,
	)
}

// PerfioctlPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfioctlPrograms struct {
	TracepointSyscallsSysEnterIoctl *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ioctl"`
}

func (p *PerfioctlPrograms) Close() error {
	return _PerfioctlClose(
		p.TracepointSyscallsSysEnterIoctl,
	)
}

func _PerfioctlClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfioctl_bpfel.o
var _PerfioctlBytes []byte
