// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfmemfdMemfdEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Name        [64]int8
	Flags       uint32
	Fd          int32
	_           [4]byte
}

// LoadPerfmemfd returns the embedded CollectionSpec for Perfmemfd.
func LoadPerfmemfd() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfmemfdBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfmemfd: %w", err)
	}

	return spec, err
}

// LoadPerfmemfdObjects loads Perfmemfd and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfmemfdObjects
//	*PerfmemfdPrograms
//	*PerfmemfdMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfmemfdObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfmemfd()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfmemfdSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmemfdSpecs struct {
	PerfmemfdProgramSpecs
	PerfmemfdMapSpecs
}

// PerfmemfdSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmemfdProgramSpecs struct {
	TracepointSyscallsSysEnterExecveat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execveat"`
	TracepointSyscallsSysEnterMemfdCreate *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_memfd_create"`
	TracepointSyscallsSysExitMemfdCreate  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_memfd_create"`
}

// PerfmemfdMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmemfdMapSpecs struct {
	DiscardComms    *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids     *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats    *ebpf.MapSpec `ebpf:"discard_stats"`
	MemfdEvents     *ebpf.MapSpec `ebpf:"memfd_events"`
	MemfdEventsHeap *ebpf.MapSpec `ebpf:"memfd_events_heap"`
}

// PerfmemfdObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmemfdObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmemfdObjects struct {
	PerfmemfdPrograms
	PerfmemfdMaps
}

func (o *PerfmemfdObjects) Close() error {
	return _PerfmemfdClose(
		&o.PerfmemfdPrograms,
		&o.PerfmemfdMaps,
	)
}

// PerfmemfdMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmemfdObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmemfdMaps struct {
	DiscardComms    *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.Map `ebpf:"discard_config"`
	DiscardPids     *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats    *ebpf.Map `ebpf:"discard_stats"`
	MemfdEvents     *ebpf.Map `ebpf:"memfd_events"`
	MemfdEventsHeap *ebpf.Map `ebpf:"memfd_events_heap"`
}

func (m *PerfmemfdMaps) Close() error {
	return _PerfmemfdClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.MemfdEvents,
		m.MemfdEventsHeap,
	)
}

// PerfmemfdPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmemfdObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmemfdPrograms struct {
	TracepointSyscallsSysEnterExecveat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execveat"`
	TracepointSyscallsSysEnterMemfdCreate *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_memfd_create"`
	TracepointSyscallsSysExitMemfdCreate  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_memfd_create"`
}

func (p *PerfmemfdPrograms) Close() error {
	return _PerfmemfdClose(
		p.TracepointSyscallsSysEnterExecveat,
		p.TracepointSyscallsSysEnterMemfdCreate,
		p.TracepointSyscallsSysExitMemfdCreate,
	)
}

func _PerfmemfdClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfmemfd_bpfel.o
var _PerfmemfdBytes []byte
