// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfcapsCapsetEvent struct {
	TimestampNs    uint64
	EventType      uint32
	Pid            uint32
	Ppid           uint32
	Uid            uint32
	Gid            uint32
	Comm           [16]int8
	TargetPid      uint32
	CapVersion     uint32
	_              [4]byte
	CapEffective   uint64
	CapPermitted   uint64
	CapInheritable uint64
	RetCode        int32
	_              [4]byte
}

// LoadPerfcaps returns the embedded CollectionSpec for Perfcaps.
func LoadPerfcaps() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfcapsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfcaps: %w", err)
	}

	return spec, err
}

// LoadPerfcapsObjects loads Perfcaps and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfcapsObjects
//	*PerfcapsPrograms
//	*PerfcapsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfcapsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfcaps()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfcapsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfcapsSpecs struct {
	PerfcapsProgramSpecs
	PerfcapsMapSpecs
}

// PerfcapsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfcapsProgramSpecs struct {
	TracepointSyscallsSysEnterCapset *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_capset"`
}

// PerfcapsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfcapsMapSpecs struct {
	CapsetEvents     *ebpf.MapSpec `ebpf:"capset_events"`
	CapsetEventsHeap *ebpf.MapSpec `ebpf:"capset_events_heap"`
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
}

// PerfcapsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfcapsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfcapsObjects struct {
	PerfcapsPrograms
	PerfcapsMaps
}

func (o *PerfcapsObjects) Close() error {
	return _PerfcapsClose(
		&o.PerfcapsPrograms,
		&o.PerfcapsMaps,
	)
}

// PerfcapsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfcapsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfcapsMaps struct {
	CapsetEvents     *ebpf.Map `ebpf:"capset_events"`
	CapsetEventsHeap *ebpf.Map `ebpf:"capset_events_heap"`
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
}

func (m *PerfcapsMaps) Close() error {
	return _PerfcapsClose(
		m.CapsetEvents,
		m.CapsetEventsHeap,
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
	)
}

// PerfcapsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfcapsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfcapsPrograms struct {
	TracepointSyscallsSysEnterCapset *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_capset"`
}

func (p *PerfcapsPrograms) Close() error {
	return _PerfcapsClose(
		p.TracepointSyscallsSysEnterCapset,
	)
}

func _PerfcapsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfcaps_bpfel.o
var _PerfcapsBytes []byte
