// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfimdsImdsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Family      uint16
	Dport       uint16
	Daddr       [16]uint8
}

// LoadPerfimds returns the embedded CollectionSpec for Perfimds.
func LoadPerfimds() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfimdsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfimds: %w", err)
	}

	return spec, err
}

// LoadPerfimdsObjects loads Perfimds and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfimdsObjects
//	*PerfimdsPrograms
//	*PerfimdsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfimdsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfimds()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfimdsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfimdsSpecs struct {
	PerfimdsProgramSpecs
	PerfimdsMapSpecs
}

// PerfimdsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfimdsProgramSpecs struct {
	TracepointSyscallsSysEnterConnect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

// PerfimdsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfimdsMapSpecs struct {
	DiscardComms   *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig  *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids    *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats   *ebpf.MapSpec `ebpf:"discard_stats"`
	ImdsEvents     *ebpf.MapSpec `ebpf:"imds_events"`
	ImdsEventsHeap *ebpf.MapSpec `ebpf:"imds_events_heap"`
}

// PerfimdsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfimdsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfimdsObjects struct {
	PerfimdsPrograms
	PerfimdsMaps
}

func (o *PerfimdsObjects) Close() error {
	return _PerfimdsClose(
		&o.PerfimdsPrograms,
		&o.PerfimdsMaps,
	)
}

// PerfimdsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfimdsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfimdsMaps struct {
	DiscardComms   *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig  *ebpf.Map `ebpf:"discard_config"`
	DiscardPids    *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats   *ebpf.Map `ebpf:"discard_stats"`
	ImdsEvents     *ebpf.Map `ebpf:"imds_events"`
	ImdsEventsHeap *ebpf.Map `ebpf:"imds_events_heap"`
}

func (m *PerfimdsMaps) Close() error {
	return _PerfimdsClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.ImdsEvents,
		m.ImdsEventsHeap,
	)
}

// PerfimdsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfimdsObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfimdsPrograms struct {
	TracepointSyscallsSysEnterConnect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
}

func (p *PerfimdsPrograms) Close() error {
	return _PerfimdsClose(
		p.TracepointSyscallsSysEnterConnect,
	)
}

func _PerfimdsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfimds_bpfel.o
var _PerfimdsBytes []byte
