// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PerfmemoryMemoryEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	_           [4]byte
	Addr        uint64
	Len         uint64
	Prot        uint32
	RetCode     int32
	Flags       uint32
	Fd          int32
}

// LoadPerfmemory returns the embedded CollectionSpec for Perfmemory.
func LoadPerfmemory() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfmemoryBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Perfmemory: %w", err)
	}

	return spec, err
}

// LoadPerfmemoryObjects loads Perfmemory and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PerfmemoryObjects
//	*PerfmemoryPrograms
//	*PerfmemoryMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPerfmemoryObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPerfmemory()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PerfmemorySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmemorySpecs struct {
	PerfmemoryProgramSpecs
	PerfmemoryMapSpecs
}

// PerfmemorySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmemoryProgramSpecs struct {
	TracepointSyscallsSysEnterMmap     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mmap"`
	TracepointSyscallsSysEnterMprotect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
}

// PerfmemoryMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PerfmemoryMapSpecs struct {
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
	MemoryEvents     *ebpf.MapSpec `ebpf:"memory_events"`
	MemoryEventsHeap *ebpf.MapSpec `ebpf:"memory_events_heap"`
}

// PerfmemoryObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmemoryObjects struct {
	PerfmemoryPrograms
	PerfmemoryMaps
}

func (o *PerfmemoryObjects) Close() error {
	return _PerfmemoryClose(
		&o.PerfmemoryPrograms,
		&o.PerfmemoryMaps,
	)
}

// PerfmemoryMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmemoryMaps struct {
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
	MemoryEvents     *ebpf.Map `ebpf:"memory_events"`
	MemoryEventsHeap *ebpf.Map `ebpf:"memory_events_heap"`
}

func (m *PerfmemoryMaps) Close() error {
	return _PerfmemoryClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.MemoryEvents,
		m.MemoryEventsHeap,
	)
}

// PerfmemoryPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPerfmemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type PerfmemoryPrograms struct {
	TracepointSyscallsSysEnterMmap     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mmap"`
	TracepointSyscallsSysEnterMprotect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
}

func (p *PerfmemoryPrograms) Close() error {
	return _PerfmemoryClose(
		p.TracepointSyscallsSysEnterMmap,
		p.TracepointSyscallsSysEnterMprotect,
	)
}

func _PerfmemoryClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perfmemory_bpfeb.o
var _PerfmemoryBytes []byte
