// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type privilegePrivilegeEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	NewUid      uint32
	NewGid      uint32
	NewEuid     uint32
	NewEgid     uint32
	RetCode     int32
}

// loadPrivilege returns the embedded CollectionSpec for privilege.
func loadPrivilege() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PrivilegeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load privilege: %w", err)
	}

	return spec, err
}

// loadPrivilegeObjects loads privilege and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*privilegeObjects
//	*privilegePrograms
//	*privilegeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPrivilegeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPrivilege()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// privilegeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type privilegeSpecs struct {
	privilegeProgramSpecs
	privilegeMapSpecs
}

// privilegeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type privilegeProgramSpecs struct {
	TracepointSyscallsSysEnterSetgid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetregid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetreuid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetuid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
}

// privilegeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type privilegeMapSpecs struct {
	PrivilegeEvents *ebpf.MapSpec `ebpf:"privilege_events"`
}

// privilegeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type privilegeObjects struct {
	privilegePrograms
	privilegeMaps
}

func (o *privilegeObjects) Close() error {
	return _PrivilegeClose(
		&o.privilegePrograms,
		&o.privilegeMaps,
	)
}

// privilegeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type privilegeMaps struct {
	PrivilegeEvents *ebpf.Map `ebpf:"privilege_events"`
}

func (m *privilegeMaps) Close() error {
	return _PrivilegeClose(
		m.PrivilegeEvents,
	)
}

// privilegePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type privilegePrograms struct {
	TracepointSyscallsSysEnterSetgid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetregid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetreuid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetuid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
}

func (p *privilegePrograms) Close() error {
	return _PrivilegeClose(
		p.TracepointSyscallsSysEnterSetgid,
		p.TracepointSyscallsSysEnterSetregid,
		p.TracepointSyscallsSysEnterSetreuid,
		p.TracepointSyscallsSysEnterSetuid,
	)
}

func _PrivilegeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed privilege_bpfel.o
var _PrivilegeBytes []byte
