// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type PrivilegePrivCtx struct {
	EventType uint32
	Pid       uint32
	Ppid      uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	NewUid    uint32
	NewGid    uint32
	NewEuid   uint32
	NewEgid   uint32
}

type PrivilegePrivilegeEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	NewUid      uint32
	NewGid      uint32
	NewEuid     uint32
	NewEgid     uint32
	RetCode     int32
}

// LoadPrivilege returns the embedded CollectionSpec for Privilege.
func LoadPrivilege() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PrivilegeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Privilege: %w", err)
	}

	return spec, err
}

// LoadPrivilegeObjects loads Privilege and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PrivilegeObjects
//	*PrivilegePrograms
//	*PrivilegeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPrivilegeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPrivilege()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PrivilegeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivilegeSpecs struct {
	PrivilegeProgramSpecs
	PrivilegeMapSpecs
}

// PrivilegeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivilegeProgramSpecs struct {
	TracepointSyscallsSysEnterSetfsgid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setfsgid"`
	TracepointSyscallsSysEnterSetfsuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setfsuid"`
	TracepointSyscallsSysEnterSetgid    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetregid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetresgid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setresgid"`
	TracepointSyscallsSysEnterSetresuid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setresuid"`
	TracepointSyscallsSysEnterSetreuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetuid    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
	TracepointSyscallsSysExitSetgid     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setgid"`
	TracepointSyscallsSysExitSetregid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setregid"`
	TracepointSyscallsSysExitSetreuid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setreuid"`
	TracepointSyscallsSysExitSetuid     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setuid"`
}

// PrivilegeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PrivilegeMapSpecs struct {
	DiscardComms    *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids     *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats    *ebpf.MapSpec `ebpf:"discard_stats"`
	PrivContext     *ebpf.MapSpec `ebpf:"priv_context"`
	PrivilegeEvents *ebpf.MapSpec `ebpf:"privilege_events"`
}

// PrivilegeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivilegeObjects struct {
	PrivilegePrograms
	PrivilegeMaps
}

func (o *PrivilegeObjects) Close() error {
	return _PrivilegeClose(
		&o.PrivilegePrograms,
		&o.PrivilegeMaps,
	)
}

// PrivilegeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivilegeMaps struct {
	DiscardComms    *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig   *ebpf.Map `ebpf:"discard_config"`
	DiscardPids     *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats    *ebpf.Map `ebpf:"discard_stats"`
	PrivContext     *ebpf.Map `ebpf:"priv_context"`
	PrivilegeEvents *ebpf.Map `ebpf:"privilege_events"`
}

func (m *PrivilegeMaps) Close() error {
	return _PrivilegeClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.PrivContext,
		m.PrivilegeEvents,
	)
}

// PrivilegePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type PrivilegePrograms struct {
	TracepointSyscallsSysEnterSetfsgid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setfsgid"`
	TracepointSyscallsSysEnterSetfsuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setfsuid"`
	TracepointSyscallsSysEnterSetgid    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetregid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetresgid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setresgid"`
	TracepointSyscallsSysEnterSetresuid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setresuid"`
	TracepointSyscallsSysEnterSetreuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetuid    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
	TracepointSyscallsSysExitSetgid     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setgid"`
	TracepointSyscallsSysExitSetregid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setregid"`
	TracepointSyscallsSysExitSetreuid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setreuid"`
	TracepointSyscallsSysExitSetuid     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setuid"`
}

func (p *PrivilegePrograms) Close() error {
	return _PrivilegeClose(
		p.TracepointSyscallsSysEnterSetfsgid,
		p.TracepointSyscallsSysEnterSetfsuid,
		p.TracepointSyscallsSysEnterSetgid,
		p.TracepointSyscallsSysEnterSetregid,
		p.TracepointSyscallsSysEnterSetresgid,
		p.TracepointSyscallsSysEnterSetresuid,
		p.TracepointSyscallsSysEnterSetreuid,
		p.TracepointSyscallsSysEnterSetuid,
		p.TracepointSyscallsSysExitSetgid,
		p.TracepointSyscallsSysExitSetregid,
		p.TracepointSyscallsSysExitSetreuid,
		p.TracepointSyscallsSysExitSetuid,
	)
}

func _PrivilegeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed privilege_bpfeb.o
var _PrivilegeBytes []byte
