// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ProcesscacheEnrichedEvent struct {
	TimestampNs     uint64
	EventType       uint32
	Flags           uint32
	Pid             uint32
	Ppid            uint32
	Uid             uint32
	Gid             uint32
	Comm            [16]int8
	Exe             [256]int8
	Cmdline         [512]int8
	ParentComm      [16]int8
	ParentExe       [256]int8
	GrandparentPid  uint32
	GrandparentComm [16]int8
	ContainerId     [72]int8
	_               [4]byte
	CgroupId        uint64
	Privilege       struct {
		OldUid  uint32
		NewUid  uint32
		OldEuid uint32
		NewEuid uint32
		OldGid  uint32
		NewGid  uint32
	}
	_       [528]byte
	RetCode int32
	_       [4]byte
}

type ProcesscachePathScratch struct {
	Components [8][64]int8
	CompLen    [8]int32
	Depth      int32
}

type ProcesscacheProcessInfo struct {
	Pid             uint32
	Ppid            uint32
	Uid             uint32
	Gid             uint32
	StartTimeNs     uint64
	Comm            [16]int8
	Exe             [256]int8
	Cmdline         [512]int8
	ParentPid       uint32
	ParentComm      [16]int8
	ParentExe       [256]int8
	GrandparentPid  uint32
	GrandparentComm [16]int8
	ContainerId     [72]int8
	CgroupId        uint64
	NsPid           uint64
	Flags           uint32
	_               [4]byte
}

// LoadProcesscache returns the embedded CollectionSpec for Processcache.
func LoadProcesscache() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcesscacheBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Processcache: %w", err)
	}

	return spec, err
}

// LoadProcesscacheObjects loads Processcache and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcesscacheObjects
//	*ProcesscachePrograms
//	*ProcesscacheMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcesscacheObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcesscache()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcesscacheSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcesscacheSpecs struct {
	ProcesscacheProgramSpecs
	ProcesscacheMapSpecs
}

// ProcesscacheSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcesscacheProgramSpecs struct {
	HandleSchedProcessExec *ebpf.ProgramSpec `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.ProgramSpec `ebpf:"handle_sched_process_exit"`
	HandleSchedProcessFork *ebpf.ProgramSpec `ebpf:"handle_sched_process_fork"`
}

// ProcesscacheMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcesscacheMapSpecs struct {
	DentryScratch   *ebpf.MapSpec `ebpf:"dentry_scratch"`
	EnrichedEvents  *ebpf.MapSpec `ebpf:"enriched_events"`
	ProcInfoScratch *ebpf.MapSpec `ebpf:"proc_info_scratch"`
	ProcessCache    *ebpf.MapSpec `ebpf:"process_cache"`
}

// ProcesscacheObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcesscacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcesscacheObjects struct {
	ProcesscachePrograms
	ProcesscacheMaps
}

func (o *ProcesscacheObjects) Close() error {
	return _ProcesscacheClose(
		&o.ProcesscachePrograms,
		&o.ProcesscacheMaps,
	)
}

// ProcesscacheMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcesscacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcesscacheMaps struct {
	DentryScratch   *ebpf.Map `ebpf:"dentry_scratch"`
	EnrichedEvents  *ebpf.Map `ebpf:"enriched_events"`
	ProcInfoScratch *ebpf.Map `ebpf:"proc_info_scratch"`
	ProcessCache    *ebpf.Map `ebpf:"process_cache"`
}

func (m *ProcesscacheMaps) Close() error {
	return _ProcesscacheClose(
		m.DentryScratch,
		m.EnrichedEvents,
		m.ProcInfoScratch,
		m.ProcessCache,
	)
}

// ProcesscachePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcesscacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcesscachePrograms struct {
	HandleSchedProcessExec *ebpf.Program `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.Program `ebpf:"handle_sched_process_exit"`
	HandleSchedProcessFork *ebpf.Program `ebpf:"handle_sched_process_fork"`
}

func (p *ProcesscachePrograms) Close() error {
	return _ProcesscacheClose(
		p.HandleSchedProcessExec,
		p.HandleSchedProcessExit,
		p.HandleSchedProcessFork,
	)
}

func _ProcesscacheClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processcache_bpfeb.o
var _ProcesscacheBytes []byte
