// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ProcessProcessEvent struct {
	TimestampNs   uint64
	EventType     uint32
	Pid           uint32
	Ppid          uint32
	Uid           uint32
	Gid           uint32
	Comm          [16]int8
	TargetPid     uint32
	Sig           int32
	PtraceRequest int32
	CloneFlags    uint64
	RetCode       int32
	_             [4]byte
}

// LoadProcess returns the embedded CollectionSpec for Process.
func LoadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Process: %w", err)
	}

	return spec, err
}

// LoadProcessObjects loads Process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProcessObjects
//	*ProcessPrograms
//	*ProcessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProcessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessSpecs struct {
	ProcessProgramSpecs
	ProcessMapSpecs
}

// ProcessSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessProgramSpecs struct {
	TracepointSyscallsSysEnterClone  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterKill   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterPtrace *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
	TracepointSyscallsSysEnterTgkill *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tgkill"`
	TracepointSyscallsSysEnterTkill  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tkill"`
}

// ProcessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProcessMapSpecs struct {
	DiscardComms  *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids   *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats  *ebpf.MapSpec `ebpf:"discard_stats"`
	ProcessEvents *ebpf.MapSpec `ebpf:"process_events"`
}

// ProcessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessObjects struct {
	ProcessPrograms
	ProcessMaps
}

func (o *ProcessObjects) Close() error {
	return _ProcessClose(
		&o.ProcessPrograms,
		&o.ProcessMaps,
	)
}

// ProcessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessMaps struct {
	DiscardComms  *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig *ebpf.Map `ebpf:"discard_config"`
	DiscardPids   *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats  *ebpf.Map `ebpf:"discard_stats"`
	ProcessEvents *ebpf.Map `ebpf:"process_events"`
}

func (m *ProcessMaps) Close() error {
	return _ProcessClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.ProcessEvents,
	)
}

// ProcessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProcessPrograms struct {
	TracepointSyscallsSysEnterClone  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterKill   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterPtrace *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
	TracepointSyscallsSysEnterTgkill *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tgkill"`
	TracepointSyscallsSysEnterTkill  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tkill"`
}

func (p *ProcessPrograms) Close() error {
	return _ProcessClose(
		p.TracepointSyscallsSysEnterClone,
		p.TracepointSyscallsSysEnterKill,
		p.TracepointSyscallsSysEnterPtrace,
		p.TracepointSyscallsSysEnterTgkill,
		p.TracepointSyscallsSysEnterTkill,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfeb.o
var _ProcessBytes []byte
