// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type processProcessEvent struct {
	TimestampNs   uint64
	EventType     uint32
	Pid           uint32
	Ppid          uint32
	Uid           uint32
	Gid           uint32
	Comm          [16]int8
	TargetPid     uint32
	Sig           int32
	PtraceRequest int32
	CloneFlags    uint64
	RetCode       int32
	_             [4]byte
}

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
}

// processSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	TracepointSyscallsSysEnterClone  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterKill   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterPtrace *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	ProcessEvents *ebpf.MapSpec `ebpf:"process_events"`
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	ProcessEvents *ebpf.Map `ebpf:"process_events"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.ProcessEvents,
	)
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	TracepointSyscallsSysEnterClone  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterKill   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterPtrace *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.TracepointSyscallsSysEnterClone,
		p.TracepointSyscallsSysEnterKill,
		p.TracepointSyscallsSysEnterPtrace,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfeb.o
var _ProcessBytes []byte
