// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SshlockdowntcLpmV4Key struct {
	Prefixlen uint32
	Data      [4]uint8
}

type SshlockdowntcLpmV6Key struct {
	Prefixlen uint32
	Data      [16]uint8
}

// LoadSshlockdowntc returns the embedded CollectionSpec for Sshlockdowntc.
func LoadSshlockdowntc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SshlockdowntcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sshlockdowntc: %w", err)
	}

	return spec, err
}

// LoadSshlockdowntcObjects loads Sshlockdowntc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SshlockdowntcObjects
//	*SshlockdowntcPrograms
//	*SshlockdowntcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSshlockdowntcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSshlockdowntc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SshlockdowntcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SshlockdowntcSpecs struct {
	SshlockdowntcProgramSpecs
	SshlockdowntcMapSpecs
}

// SshlockdowntcSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SshlockdowntcProgramSpecs struct {
	SshLockdownTc *ebpf.ProgramSpec `ebpf:"ssh_lockdown_tc"`
}

// SshlockdowntcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SshlockdowntcMapSpecs struct {
	SshLockdownTcPorts       *ebpf.MapSpec `ebpf:"ssh_lockdown_tc_ports"`
	SshLockdownTcState       *ebpf.MapSpec `ebpf:"ssh_lockdown_tc_state"`
	SshLockdownTcStats       *ebpf.MapSpec `ebpf:"ssh_lockdown_tc_stats"`
	SshLockdownTcV4Allowlist *ebpf.MapSpec `ebpf:"ssh_lockdown_tc_v4_allowlist"`
	SshLockdownTcV6Allowlist *ebpf.MapSpec `ebpf:"ssh_lockdown_tc_v6_allowlist"`
}

// SshlockdowntcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSshlockdowntcObjects or ebpf.CollectionSpec.LoadAndAssign.
type SshlockdowntcObjects struct {
	SshlockdowntcPrograms
	SshlockdowntcMaps
}

func (o *SshlockdowntcObjects) Close() error {
	return _SshlockdowntcClose(
		&o.SshlockdowntcPrograms,
		&o.SshlockdowntcMaps,
	)
}

// SshlockdowntcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSshlockdowntcObjects or ebpf.CollectionSpec.LoadAndAssign.
type SshlockdowntcMaps struct {
	SshLockdownTcPorts       *ebpf.Map `ebpf:"ssh_lockdown_tc_ports"`
	SshLockdownTcState       *ebpf.Map `ebpf:"ssh_lockdown_tc_state"`
	SshLockdownTcStats       *ebpf.Map `ebpf:"ssh_lockdown_tc_stats"`
	SshLockdownTcV4Allowlist *ebpf.Map `ebpf:"ssh_lockdown_tc_v4_allowlist"`
	SshLockdownTcV6Allowlist *ebpf.Map `ebpf:"ssh_lockdown_tc_v6_allowlist"`
}

func (m *SshlockdowntcMaps) Close() error {
	return _SshlockdowntcClose(
		m.SshLockdownTcPorts,
		m.SshLockdownTcState,
		m.SshLockdownTcStats,
		m.SshLockdownTcV4Allowlist,
		m.SshLockdownTcV6Allowlist,
	)
}

// SshlockdowntcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSshlockdowntcObjects or ebpf.CollectionSpec.LoadAndAssign.
type SshlockdowntcPrograms struct {
	SshLockdownTc *ebpf.Program `ebpf:"ssh_lockdown_tc"`
}

func (p *SshlockdowntcPrograms) Close() error {
	return _SshlockdowntcClose(
		p.SshLockdownTc,
	)
}

func _SshlockdowntcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sshlockdowntc_bpfeb.o
var _SshlockdowntcBytes []byte
