// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SshlockdownLpmV4Key struct {
	Prefixlen uint32
	Data      [4]uint8
}

type SshlockdownLpmV6Key struct {
	Prefixlen uint32
	Data      [16]uint8
}

// LoadSshlockdown returns the embedded CollectionSpec for Sshlockdown.
func LoadSshlockdown() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SshlockdownBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Sshlockdown: %w", err)
	}

	return spec, err
}

// LoadSshlockdownObjects loads Sshlockdown and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SshlockdownObjects
//	*SshlockdownPrograms
//	*SshlockdownMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSshlockdownObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSshlockdown()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SshlockdownSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SshlockdownSpecs struct {
	SshlockdownProgramSpecs
	SshlockdownMapSpecs
}

// SshlockdownSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SshlockdownProgramSpecs struct {
	SshlockdownSocketAccept *ebpf.ProgramSpec `ebpf:"sshlockdown_socket_accept"`
}

// SshlockdownMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SshlockdownMapSpecs struct {
	SshLockdownPorts       *ebpf.MapSpec `ebpf:"ssh_lockdown_ports"`
	SshLockdownState       *ebpf.MapSpec `ebpf:"ssh_lockdown_state"`
	SshLockdownStats       *ebpf.MapSpec `ebpf:"ssh_lockdown_stats"`
	SshLockdownV4Allowlist *ebpf.MapSpec `ebpf:"ssh_lockdown_v4_allowlist"`
	SshLockdownV6Allowlist *ebpf.MapSpec `ebpf:"ssh_lockdown_v6_allowlist"`
}

// SshlockdownObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSshlockdownObjects or ebpf.CollectionSpec.LoadAndAssign.
type SshlockdownObjects struct {
	SshlockdownPrograms
	SshlockdownMaps
}

func (o *SshlockdownObjects) Close() error {
	return _SshlockdownClose(
		&o.SshlockdownPrograms,
		&o.SshlockdownMaps,
	)
}

// SshlockdownMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSshlockdownObjects or ebpf.CollectionSpec.LoadAndAssign.
type SshlockdownMaps struct {
	SshLockdownPorts       *ebpf.Map `ebpf:"ssh_lockdown_ports"`
	SshLockdownState       *ebpf.Map `ebpf:"ssh_lockdown_state"`
	SshLockdownStats       *ebpf.Map `ebpf:"ssh_lockdown_stats"`
	SshLockdownV4Allowlist *ebpf.Map `ebpf:"ssh_lockdown_v4_allowlist"`
	SshLockdownV6Allowlist *ebpf.Map `ebpf:"ssh_lockdown_v6_allowlist"`
}

func (m *SshlockdownMaps) Close() error {
	return _SshlockdownClose(
		m.SshLockdownPorts,
		m.SshLockdownState,
		m.SshLockdownStats,
		m.SshLockdownV4Allowlist,
		m.SshLockdownV6Allowlist,
	)
}

// SshlockdownPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSshlockdownObjects or ebpf.CollectionSpec.LoadAndAssign.
type SshlockdownPrograms struct {
	SshlockdownSocketAccept *ebpf.Program `ebpf:"sshlockdown_socket_accept"`
}

func (p *SshlockdownPrograms) Close() error {
	return _SshlockdownClose(
		p.SshlockdownSocketAccept,
	)
}

func _SshlockdownClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sshlockdown_bpfeb.o
var _SshlockdownBytes []byte
