// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type VfshooksPathScratch struct {
	Components [8][64]int8
	CompLen    [8]int32
	Depth      int32
}

type VfshooksVfsEvent struct {
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Comm        [16]int8
	Path        [256]int8
	Path2       [256]int8
	I_mode      uint32
	I_uid       uint32
	_           [4]byte
	I_ino       uint64
	RetCode     int32
	_           [4]byte
}

// LoadVfshooks returns the embedded CollectionSpec for Vfshooks.
func LoadVfshooks() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VfshooksBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Vfshooks: %w", err)
	}

	return spec, err
}

// LoadVfshooksObjects loads Vfshooks and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*VfshooksObjects
//	*VfshooksPrograms
//	*VfshooksMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadVfshooksObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadVfshooks()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// VfshooksSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VfshooksSpecs struct {
	VfshooksProgramSpecs
	VfshooksMapSpecs
}

// VfshooksSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VfshooksProgramSpecs struct {
	KprobeSecurityInodeSetattr *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_setattr"`
	KprobeVfsOpen              *ebpf.ProgramSpec `ebpf:"kprobe_vfs_open"`
	KprobeVfsRename            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_rename"`
	KprobeVfsUnlink            *ebpf.ProgramSpec `ebpf:"kprobe_vfs_unlink"`
}

// VfshooksMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VfshooksMapSpecs struct {
	DiscardComms     *ebpf.MapSpec `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.MapSpec `ebpf:"discard_config"`
	DiscardPids      *ebpf.MapSpec `ebpf:"discard_pids"`
	DiscardStats     *ebpf.MapSpec `ebpf:"discard_stats"`
	VfsDentryScratch *ebpf.MapSpec `ebpf:"vfs_dentry_scratch"`
	VfsEvents        *ebpf.MapSpec `ebpf:"vfs_events"`
}

// VfshooksObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadVfshooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type VfshooksObjects struct {
	VfshooksPrograms
	VfshooksMaps
}

func (o *VfshooksObjects) Close() error {
	return _VfshooksClose(
		&o.VfshooksPrograms,
		&o.VfshooksMaps,
	)
}

// VfshooksMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadVfshooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type VfshooksMaps struct {
	DiscardComms     *ebpf.Map `ebpf:"discard_comms"`
	DiscardConfig    *ebpf.Map `ebpf:"discard_config"`
	DiscardPids      *ebpf.Map `ebpf:"discard_pids"`
	DiscardStats     *ebpf.Map `ebpf:"discard_stats"`
	VfsDentryScratch *ebpf.Map `ebpf:"vfs_dentry_scratch"`
	VfsEvents        *ebpf.Map `ebpf:"vfs_events"`
}

func (m *VfshooksMaps) Close() error {
	return _VfshooksClose(
		m.DiscardComms,
		m.DiscardConfig,
		m.DiscardPids,
		m.DiscardStats,
		m.VfsDentryScratch,
		m.VfsEvents,
	)
}

// VfshooksPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadVfshooksObjects or ebpf.CollectionSpec.LoadAndAssign.
type VfshooksPrograms struct {
	KprobeSecurityInodeSetattr *ebpf.Program `ebpf:"kprobe_security_inode_setattr"`
	KprobeVfsOpen              *ebpf.Program `ebpf:"kprobe_vfs_open"`
	KprobeVfsRename            *ebpf.Program `ebpf:"kprobe_vfs_rename"`
	KprobeVfsUnlink            *ebpf.Program `ebpf:"kprobe_vfs_unlink"`
}

func (p *VfshooksPrograms) Close() error {
	return _VfshooksClose(
		p.KprobeSecurityInodeSetattr,
		p.KprobeVfsOpen,
		p.KprobeVfsRename,
		p.KprobeVfsUnlink,
	)
}

func _VfshooksClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed vfshooks_bpfel.o
var _VfshooksBytes []byte
