#!/bin/sh
#
# chkconfig: 345 85 15     - start or stop process definition within the boot process
# description: AlertPriority monitoring agent
# processname: alertpriority-agent
# pidfile: /var/run/alertpriority-agent.pid

NAME=alertpriority-agent
DAEMON=/usr/bin/alertpriority-agent
PIDFILE=/var/run/alertpriority-agent.pid
LOG=/var/log/alertpriority-agent.log
export TMPDIR=/var/lib

# Source function library.      This creates the operating environment for the process to be started
. /etc/init.d/functions

case "$1" in
  start)
        echo -n "Starting $DAEMON: "
        daemon $DAEMON -D -p $PIDFILE -l $LOG
        echo
        touch /var/lock/subsys/process-name
        ;;
  stop)
        echo -n "Shutting down $DAEMON: "
        killproc $DAEMON
        echo
        rm -f $PIDFILE
        ;;
  status)
        status $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  reload)
        echo -n "Reloading $DAEMON: "
        killproc $DAEMON -HUP
        echo
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
